/* Export — Excel workbook with live formulas, assessment JSON for crg_calc.py / build_workbook.py,
   workspace backup, and the context pack for the CyberRiskGuardian agent. © 2026 Marc-André Léger. CC BY-NC 4.0 */
'use strict';
import { GENERATOR } from '../version.js';
import { el, n0, n2, card, banner, download, toast, copyText, kpi, select, field, pill, pillFor, table, money } from '../util.js';
import { S, compute, exportAssessment, docText, saveNow } from '../state.js';
import { buildWorkbook, exportRows, SCOPES, OPTIONAL_SHEETS } from '../exportx.js';
import { exportWorkspace } from './org.js';
import { techName } from '../ontology.js';

const safe = s => (s || 'assessment').replace(/[^\w.-]+/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');

export function render(sec) {
  const ws = S.ws, R = compute();
  sec.replaceChildren(el('h1', null, 'Export'),
    el('p', 'lede', 'Take the assessment out of the app. Files are generated locally and saved through your browser\'s download — nothing is uploaded.'));
  sec.append(el('div', 'grid g4', kpi('Scenarios', `${R.inc.length} included / ${R.rows.length}`), kpi('Initiatives', n0(ws.assessment.INITIATIVES.length)),
    kpi('Vulnerabilities', n0(ws.vulns.length)), kpi('KRI measurements', n0((ws.kriHistory || []).length))));

  sec.append(excelCard(R));

  sec.append(card(el('h2', null, 'Assessment JSON'),
    el('p', null, 'The data model read by ', el('span', 'mono', 'crg_calc.py'), ', ', el('span', 'mono', 'build_workbook.py'), ' and the CyberRiskGuardian plugin. ATT&CK, CWE and CVE links travel as optional fields and do not change any total.'),
    el('div', 'btnrow', el('button', { class: 'btn ghost', onclick: () => download(safe(ws.org.name || ws.name) + '-assessment.json', JSON.stringify(exportAssessment(ws), null, 1), 'application/json') }, 'All scenarios'),
      el('button', { class: 'btn ghost', onclick: () => download(safe(ws.org.name || ws.name) + '-assessment-included.json', JSON.stringify(exportAssessment(ws, { includedOnly: true }), null, 1), 'application/json') }, 'Included scenarios only'))));

  sec.append(card(el('h2', null, 'Context pack for the CyberRiskGuardian agent'),
    el('p', null, 'A Markdown brief — organization profile, crown jewels, obligations, document text, current scenarios and KRIs — to hand to the CyberRiskGuardian plugin in Claude (', el('span', 'mono', '/risk-assessment'), ', ', el('span', 'mono', '/select-scenarios'), ') so it can draft scenarios and estimates from your evidence. This app itself uses no AI and sends nothing.'),
    banner('warn', 'Check before sharing', 'The pack contains the full text of uploaded documents. Only give it to an AI service your organization has authorized for this data.'),
    el('div', 'btnrow', el('button', { class: 'btn ghost', onclick: async () => download(safe(ws.org.name || ws.name) + '-context-pack.md', await contextPack(), 'text/markdown') }, 'Download context pack'),
      el('button', { class: 'btn ghost', onclick: async e => copyText(await contextPack(), e.target) }, 'Copy to clipboard'))));

  sec.append(card(el('h2', null, 'Workspace backup'),
    el('p', null, 'Everything in this workspace — profile, documents with their text, scenarios, links, decisions, KRI history and the revision log — as one JSON file. Import it under Organization → Workspaces on this or another computer. The threat-context snapshot is not included; download it from the Threat context screen.'),
    el('div', 'btnrow', el('button', { class: 'btn ghost', onclick: async () => { await saveNow(); exportWorkspace(ws); } }, 'Export workspace'))));
}

export async function contextPack() {
  const ws = S.ws, o = ws.org, a = ws.assessment, R = compute();
  const L = [];
  L.push(`# Context pack — ${o.name || ws.name}`, '', `Generated by ${GENERATOR} on ${new Date().toISOString().slice(0, 10)}. Workspace type: ${ws.kind}.`,
    ws.kind !== 'organization' ? '> Teaching case: the organization and its data are fictional.' : '', '',
    '## Instructions for the CyberRiskGuardian agent', '',
    'Use this pack as the primary evidence for a CyberRiskGuardian assessment over the ' + (a.PERIOD || 'next 12 months') + '. Distinguish documented facts, assumptions, analyst estimates and information gaps. Label provisional values "Analytical estimate — validation required." Generate 20 candidate scenarios as causal chains, select the 10 most material, quantify Pb(A), Pb(ψ,A), δe, δm, θ, μ(E) with confidence levels, use CVSS v4.0 Base only, and return the result as assessment JSON (keys APPETITE, FACTOR, SCEN[...]) with optional `attack`, `cwe` and `cves` arrays per scenario so it can be loaded back into the desktop app.', '',
    '## Organization profile', '');
  const f = (k, v) => v ? L.push(`- **${k}:** ${String(v).replace(/\n/g, ' ')}`) : null;
  f('Sector', o.sector); f('Size', o.size); f('Region', o.region); f('Mission', o.mission); f('Products and services', o.services); f('Critical processes', o.processes);
  f('Critical systems', o.systems); f('Cloud', o.cloud); f('Suppliers', o.suppliers); f('Obligations', (o.regulations || []).join('; ')); f('Sensitive information', o.sensitive);
  f('Availability requirements', o.availability); f('Controls and maturity', o.maturity); f('Incident history', o.incidents);
  f('Risk appetite', `${a.APPETITE}${ws.appetite_rationale ? ' — ' + ws.appetite_rationale : ''}`);
  if (ws.budget?.it_budget) f('IT budget / cyber spend', `${money(ws.budget.it_budget, a.CURRENCY)} / ${money(ws.budget.spend, a.CURRENCY)} ${a.CURRENCY || ''}`);
  if (ws.classroom) { L.push('', '## Classroom setting', ''); for (const [k, v] of Object.entries(ws.classroom)) f(k, v); }
  if ((a.CROWN || []).length) {
    L.push('', '## Crown jewels', '', '| ID | Asset / service | Role | Owner | C | I | A | Dependencies |', '|---|---|---|---|---|---|---|---|');
    for (const r of a.CROWN) L.push('| ' + [0, 1, 2, 3, 4, 5, 6, 7].map(i => String(r[i] || '').replace(/\|/g, '/').replace(/\n/g, ' ')).join(' | ') + ' |');
  }
  if (R.rows.length) {
    L.push('', `## Current scenarios (${R.rows.length})`, '');
    for (const r of R.rows) L.push(`- **${r.id}** ${r.name} — ratio ${r.ratio.toFixed(2)} (${r.cls})${r.inc ? '' : ' [excluded]'}${(r.s.attack || []).length ? ' — ATT&CK ' + r.s.attack.map(t => `${t} ${techName(t)}`).join(', ') : ''}`);
  }
  const exp = ws.vulns.filter(v => v.exposed);
  if (exp.length) { L.push('', '## Vulnerabilities with confirmed exposure', ''); for (const v of exp) L.push(`- ${v.id} ${[v.product, v.asset].filter(Boolean).join(' — ')}`); }
  if (ws.snapshot) L.push('', '## Threat context', '', `Snapshot ${ws.snapshot.name}, retrieved ${ws.snapshot.retrieved}, expires ${ws.snapshot.expires}; ${n0(ws.snapshot.kev)} KEV entries, ${n0(ws.snapshot.epss)} EPSS scores.`);
  if (ws.docs.length) {
    L.push('', '## Context documents', '');
    for (const d of ws.docs) {
      const t = await docText(d.id);
      L.push(`### ${d.name}`, '', `Category: ${d.category}. ${n0(d.words)} words.`, '', t.length > 60000 ? t.slice(0, 60000) + '\n\n[… truncated at 60,000 characters]' : t, '');
    }
  }
  return L.filter(x => x !== null).join('\n');
}

/* ---------------- Excel: regenerate from scratch with options ---------------- */
const xo = { scope: 'included', picked: null, sheets: null, years: null, kriHistory: true, q: '' };
function excelCard(R) {
  const ws = S.ws;
  if (!xo.picked) xo.picked = R.inc.map(r => r.id);
  if (!xo.sheets) xo.sheets = OPTIONAL_SHEETS.slice();
  if (!xo.years) xo.years = (ws.budgetYears || []).map(y => y.year);
  const msg = el('div'), preview = el('div', 'note'), pickBox = el('div');
  const counts = Object.fromEntries(Object.keys(SCOPES).map(k => [k, k === 'picked' ? xo.picked.length : exportRows({ scope: k }).length]));
  const scopeBox = el('div', 'grid g3');
  for (const [k, [label]] of Object.entries(SCOPES)) {
    const rb = el('input', { type: 'radio', name: 'xscope', value: k, checked: xo.scope === k });
    rb.addEventListener('change', () => { xo.scope = k; drawPick(); upd(); });
    scopeBox.append(el('label', { class: 'opt', style: { display: 'flex', gap: '10px', alignItems: 'center', justifyContent: 'flex-start', textAlign: 'left', color: 'var(--ink)', fontSize: '13px', cursor: 'pointer', margin: 0 } }, rb, el('span', { style: { flex: '1' } }, label, el('div', 'small muted', k === 'picked' ? 'choose below' : `${counts[k]} scenario(s)`))));
  }
  const drawPick = () => {
    pickBox.replaceChildren();
    if (xo.scope !== 'picked') return;
    const q = el('input', { placeholder: 'Search scenarios — ID, name, threat, CWE, CVE, owner…', value: xo.q });
    const holder = el('div', 'scroll-y', { style: { maxHeight: '320px', marginTop: '8px' } });
    const match = r => !xo.q || [r.id, r.name, r.s.threat_source, r.s.owner, ...(r.s.attack || []), ...(r.s.cwe || []), ...(r.s.cves || [])].join(' ').toLowerCase().includes(xo.q.toLowerCase());
    const draw = () => {
      const rows = R.rows.filter(match);
      holder.replaceChildren(...rows.map(r => {
        const c = el('input', { type: 'checkbox', checked: xo.picked.includes(r.id) });
        c.addEventListener('change', () => { const set = new Set(xo.picked); c.checked ? set.add(r.id) : set.delete(r.id); xo.picked = R.rows.map(x => x.id).filter(id => set.has(id)); upd(); });
        return el('label', { style: { display: 'flex', gap: '8px', alignItems: 'center', color: 'var(--ink)', fontSize: '13px', padding: '4px 0', borderBottom: '1px solid var(--line)' } }, c, el('span', 'mono small', r.id), (r.name || '').slice(0, 80), ' ', pill(r.cls, pillFor(r.cls)));
      }));
    };
    q.addEventListener('input', () => { xo.q = q.value; draw(); });
    const bulk = (fn) => { const shown = R.rows.filter(match).map(r => r.id); const set = new Set(xo.picked); for (const id of shown) fn(set, id); xo.picked = R.rows.map(x => x.id).filter(id => set.has(id)); draw(); upd(); };
    pickBox.append(el('div', 'filterbar', { style: { marginTop: '12px' } }, el('div', 'grow', q),
      el('button', { class: 'btn sm ghost', onclick: () => bulk((s2, id) => s2.add(id)) }, 'Pick shown'),
      el('button', { class: 'btn sm ghost', onclick: () => bulk((s2, id) => s2.delete(id)) }, 'Unpick shown'),
      el('button', { class: 'btn sm ghost', onclick: () => { xo.picked = R.inc.map(r => r.id); draw(); upd(); } }, 'Start from the calculator selection')), holder);
    draw();
  };
  const sheetBox = el('div', 'chips');
  for (const sh of OPTIONAL_SHEETS) {
    const c = el('input', { type: 'checkbox', checked: xo.sheets.includes(sh) });
    c.addEventListener('change', () => { const set = new Set(xo.sheets); c.checked ? set.add(sh) : set.delete(sh); xo.sheets = OPTIONAL_SHEETS.filter(x => set.has(x)); upd(); });
    sheetBox.append(el('label', { class: 'chip', style: { cursor: 'pointer' } }, c, sh));
  }
  const yearBox = el('div', 'chips');
  for (const y of ws.budgetYears || []) {
    const c = el('input', { type: 'checkbox', checked: xo.years.includes(y.year) });
    c.addEventListener('change', () => { const set = new Set(xo.years); c.checked ? set.add(y.year) : set.delete(y.year); xo.years = [...set].sort(); upd(); });
    yearBox.append(el('label', { class: 'chip', style: { cursor: 'pointer' } }, c, String(y.year)));
  }
  const kh = el('input', { type: 'checkbox', checked: xo.kriHistory });
  kh.addEventListener('change', () => { xo.kriHistory = kh.checked; upd(); });
  const upd = () => {
    const n = exportRows({ scope: xo.scope, picked: xo.picked }).length;
    const sheets = 5 + xo.sheets.filter(x => x !== 'KRI_History' || xo.kriHistory).length;
    preview.replaceChildren(el('b', null, `This export: ${n} scenario(s), ${sheets} sheets`), ` — README, Parameters, Inputs, Analyse and Portfolio always included${xo.sheets.includes('Budget') ? `; budget years ${xo.years.join(', ') || 'none'}` : ''}.`);
    goBtn.disabled = n === 0;
  };
  const goBtn = el('button', { class: 'btn', id: 'xlsx-go', onclick: async e => {
    const b = e.target; b.disabled = true; b.textContent = 'Building…';
    try {
      const { wb, n } = await buildWorkbook({ scope: xo.scope, picked: xo.picked, sheets: xo.sheets, years: xo.years, kriHistory: xo.kriHistory });
      const blob = await wb.blob();
      const tag = { included: 'included', all: 'all', above: 'above-tolerance', aboveat: 'above-or-at-tolerance', picked: 'selection' }[xo.scope];
      download(safe(ws.org.name || ws.name) + '_CyberRiskGuardian_Workbook_' + tag + '.xlsx', blob);
      msg.replaceChildren(banner('good', 'Workbook regenerated', `${n} scenarios, ${wb.sheets.length} sheets, ${(blob.size / 1024).toFixed(0)} KB, built from scratch from the current workspace. Excel recalculates on open; values shown before recalculation were computed by the verified engine.`));
    } catch (err) { console.error(err); msg.replaceChildren(banner('bad', 'Export failed', String(err.stack || err))); }
    b.textContent = 'Regenerate the Excel workbook'; upd();
  } }, 'Regenerate the Excel workbook');
  drawPick();
  const c = card(el('h2', null, 'Excel workbook (.xlsx) — regenerate from scratch'),
    el('p', null, 'Every export builds a new workbook from the current workspace, with live formulas — Parameters, Inputs, Analyse, Portfolio, Sensitivity and Case_View laid out as ', el('span', 'mono', 'build_workbook.py'), ' produces them, plus the sheets you choose. Change a blue input in Excel and every dependent cell recalculates. Shared initiative costs are split across the exported scenarios.'),
    el('h2', null, 'Scenarios'), scopeBox, pickBox,
    el('h2', null, 'Sheets'), sheetBox,
    (ws.budgetYears || []).length ? el('div', null, el('h2', null, 'Budget years'), yearBox) : null,
    el('label', { style: { display: 'flex', gap: '8px', alignItems: 'center', color: 'var(--ink)', marginTop: '12px' } }, kh, 'Include the KRI measurement history'),
    el('div', 'btnrow', { style: { marginTop: '14px' } }, goBtn, preview), msg);
  upd();
  return c;
}
