# -*- coding: utf-8 -*-
"""Scenarios S11-S30, extra candidates, initiatives and KRIs for the 30-scenario assessment."""
from data import P

NEW = []
def S(**kw):
    NEW.append(kw)

S(id="S11", ref="MED-CYR-04", name="API key or secret exposed in code, logs or configuration enables direct data access",
  statement="An opportunistic actor finds an API key, database connection string or cloud access token that a developer committed to a code repository, left in a log or embedded in a configuration file, and uses it to call MediBec's EHR integration or cloud storage APIs directly, extracting patient data without passing through user authentication.",
  stakeholders="Application development team; CIO; Cybersecurity lead; Privacy officer; cloud provider; integration partners.",
  background="MediBec has in-house software/application development and database staff (E3). API key management and repository scanning are listed as an auditable area (E7) and as scenario MED-CYR-04 (E8). No secret-management tooling is evidenced.",
  threat_source="Opportunistic actor scanning public repositories and paste sites; cybercriminal.",
  threat_event="Use of a leaked credential against an API.",
  vulns=["No secret scanning or vault evidenced (E7)", "Long-lived API keys without rotation (Analyst assumption)", "API calls not monitored for anomalous volume (E7)", "Development practices and repository visibility unknown (Evidence gap)"],
  assets="CJ1 EHR integration APIs; CJ7 cloud storage.", processes="Application integration, data exchange with partners.",
  controls=["Encrypted storage (E2 - does not protect against valid-key access)"],
  narrative="A developer pushes a test script containing a storage access key to a public repository. Within hours automated scanners harvest it; an actor lists and downloads patient export files and queries an integration endpoint until the key is revoked weeks later.",
  sequence=["Discovery - automated secret scanning of public sources", "Initial access - valid API key", "Collection - API enumeration and downloads", "Exfiltration - bulk transfer", "Detection - late, via billing anomaly or external notice", "Business impact - privacy breach"],
  consequences={"Confidentiality/privacy": "Bulk access to data reachable by the key.", "Integrity": "Possible if key has write scope.", "Availability": "Key revocation may break integrations.", "Operations": "Emergency rotation across systems.", "Financial": "Notification and forensic costs.", "Regulatory": "Reportable confidentiality incident likely.", "Reputation": "Moderate to high.", "Safety": "Low."},
  params={"PbA": P(0.45, "Plausible", "Secret leakage is common where development occurs; MediBec's development footprint is uncertain.", "E3, E7", "Low"),
          "Pbx": P(0.45, "Plausible", "No vault, scanning or rotation evidenced.", "E7", "Low"),
          "De": P(0.50, "Material", "Data reachable by one key.", "E7", "Medium"),
          "Dm": P(0.80, "Severe", "Key with broad EHR or storage scope.", "E1", "Medium"),
          "Th": P(0.40, "Limited", "API monitoring not evidenced.", "E7", "Low"),
          "Mu": P(0.75, "High", "Integrations support EHR and image exchange.", "E2", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:H/VI:L/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Representative weakness: hard-coded credential (CWE-798). AT:P the attacker must first obtain the leaked secret; PR:N once held, no further privileges needed; VC:H data access; VI:L limited write scope.",
  red_p=0.85, red_i=0.60, inits=["I03", "I08", "I14"],
  treatment="Secret scanning in repositories and pipelines, central vault with short-lived tokens and rotation (I14); API anomaly monitoring (I03); scoped cloud keys (I08).",
  owner="CIO (Application development)", horizon="3-9 months")

S(id="S12", ref="MED-CYR-05", name="Clinic Wi-Fi compromise or rogue access point gives access to the clinical network",
  statement="An attacker in or near a clinic exploits weak wireless security, an unsegmented guest network or a rogue access point to join the clinic network, intercept credentials and reach EHR workstations and local storage.",
  stakeholders="Clinic managers; Infrastructure team; Cybersecurity lead; patients and visitors; Clinical Ops.",
  background="Wireless and guest networks are an auditable area; WPA settings, rogue AP scans and guest segmentation tests are expected evidence but none is documented (E7). Clinics are geographically dispersed (E1).",
  threat_source="Local attacker (visitor, patient, passer-by) or opportunistic cybercriminal.",
  threat_event="Unauthorized wireless access and lateral movement.",
  vulns=["Guest and clinical Wi-Fi segmentation not evidenced (E7)", "Wireless standard and key management unknown (Evidence gap)", "No rogue AP detection evidenced", "Flat clinic LAN (Analyst assumption, see S7)"],
  assets="Clinic LAN; CJ1 EHR workstations; local clinic storage.", processes="Clinic operations, EHR access at point of care.",
  controls=["Firewalls and IDS/IPS at the Montreal hub (E2 - clinic-level coverage unknown)"],
  narrative="A pre-shared Wi-Fi key posted in a staff room is reused on the guest network, which routes to the clinic LAN. An attacker in the waiting room scans the network, finds a file share on the local storage unit and a workstation with an open remote desktop service.",
  sequence=["Initial access - weak/shared Wi-Fi key or rogue AP", "Discovery - scan clinic LAN", "Credential access - interception of cleartext protocols", "Lateral movement - to workstation or storage", "Collection - local patient files", "Detection - unlikely at clinic level", "Business impact - local breach or foothold for S2"],
  consequences={"Confidentiality/privacy": "Local patient files; intercepted credentials.", "Integrity": "Low.", "Availability": "Low unless used for S2.", "Operations": "Wi-Fi reconfiguration at all clinics.", "Financial": "Moderate.", "Regulatory": "Possible reportable incident.", "Reputation": "Moderate.", "Safety": "Indirect."},
  params={"PbA": P(0.40, "Plausible", "Requires physical proximity; clinics have public waiting rooms.", "E1", "Low"),
          "Pbx": P(0.45, "Plausible", "Wireless controls unknown.", "E7", "Low"),
          "De": P(0.40, "Moderate", "Access limited to one clinic.", "E1", "Medium"),
          "Dm": P(0.75, "Severe", "Foothold leading to network-wide compromise.", "E2", "Medium"),
          "Th": P(0.40, "Limited", "No clinic-level wireless monitoring evidenced.", "E7", "Low"),
          "Mu": P(0.70, "High", "Clinic networks carry point-of-care EHR access.", "E1", "Medium")},
  cvss="CVSS:4.0/AV:A/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA:N/SC:H/SI:L/SA:L",
  cvss_note="Representative weakness: weak wireless authentication with guest-to-internal routing. AV:A adjacent (radio range); VC/VI:L on the WLAN itself; SC:H clinical systems reachable behind it.",
  red_p=0.80, red_i=0.65, inits=["I03", "I06"],
  treatment="WPA3-Enterprise for staff, isolated internet-only guest Wi-Fi, rogue AP detection and NAC (I06); monitoring of clinic segments (I03).",
  owner="CIO (Infrastructure)", horizon="6-18 months")

S(id="S13", ref="MED-CYR-10", name="DDoS attack disrupts online booking, patient portal and communications",
  statement="A hacktivist or extortion group floods MediBec's internet-facing services with traffic, making online appointment booking, patient records access and external communications unavailable for hours or days and pushing volume to clinic phone lines.",
  stakeholders="Clinic managers; Communications; CIO; ISP and hosting providers; patients.",
  background="MED-CYR-10 identifies online services for appointments, records access and communications (E8). No DDoS protection, CDN or WAF is documented (E2).",
  threat_source="Hacktivist or DDoS-for-extortion group.",
  threat_event="Volumetric or application-layer denial of service.",
  vulns=["No DDoS mitigation service evidenced", "Single internet egress via Montreal hub (E2)", "No provider coordination plan evidenced"],
  assets="CJ3 online services; internet connectivity for clinics.", processes="Appointment booking, patient communications.",
  controls=["Firewalls, IDS/IPS (E2 - not designed for volumetric attacks)"],
  narrative="Following media coverage of healthcare, a hacktivist botnet targets MediBec's booking site. The shared internet link saturates, also degrading clinic access to cloud services routed through Montreal.",
  sequence=["Reconnaissance - identify public services", "Attack - volumetric and HTTP flood", "Impact - saturation of shared link", "Detection - users report outage", "Response - ISP engagement without pre-arranged mitigation", "Business impact - hours to days of degraded service"],
  consequences={"Confidentiality/privacy": "None.", "Integrity": "None.", "Availability": "Online services unavailable; cloud access degraded.", "Operations": "Phone and front-desk overload.", "Financial": "Lost bookings.", "Regulatory": "Low.", "Reputation": "Moderate.", "Safety": "Low - clinics continue in person."},
  params={"PbA": P(0.50, "Plausible", "DDoS campaigns against healthcare occur; MediBec profile moderate.", "E4", "Low"),
          "Pbx": P(0.60, "Likely", "No mitigation evidenced.", "E2", "Medium"),
          "De": P(0.30, "Limited", "Hours of online unavailability.", "E8", "Medium"),
          "Dm": P(0.55, "Material", "Multi-day disruption including cloud access.", "E2", "Low"),
          "Th": P(0.45, "Moderate", "Clinics can operate without online booking.", "E1", "Medium"),
          "Mu": P(0.55, "Moderate", "Online services useful but not essential to care.", "E8", "Low")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N",
  cvss_note="Limited applicability: volumetric DDoS exploits capacity, not a software flaw. Representative weakness: service without rate limiting or upstream mitigation (CWE-770). Availability only.",
  red_p=0.80, red_i=0.70, inits=["I11", "I15"],
  treatment="Upstream DDoS mitigation, CDN and WAF for public services, separate egress for clinic cloud traffic (I15); provider escalation and communications playbook (I11).",
  owner="CIO", horizon="0-6 months")

S(id="S14", ref="Annex B #71", name="Business e-mail compromise diverts vendor or billing payments",
  statement="A fraudster spoofs or compromises a supplier or executive mailbox and instructs MediBec finance staff to change bank details or pay a fraudulent invoice, because payment-change verification and e-mail authentication are weak, resulting in direct financial loss.",
  stakeholders="Finance lead; accounts payable; CFO; suppliers; Cybersecurity lead; bank.",
  background="Billing and administrative systems are central (E1); phishing lures already target billing staff (E6). E-mail authentication (DMARC) and payment verification procedures are not documented.",
  threat_source="Organized fraud group.", threat_event="Fraudulent payment instruction.",
  vulns=["No out-of-band payment-change verification evidenced", "DMARC enforcement unknown", "Billing staff targeted by phishing (E6)"],
  assets="CJ4 billing and accounts payable.", processes="Supplier payments, patient refunds.",
  controls=["E-mail filtering (E2 - effectiveness unknown)"],
  narrative="A look-alike supplier domain sends an updated banking form before a large equipment invoice. Accounts payable updates the vendor record by e-mail; CAD 180,000 is transferred before the real supplier chases payment.",
  sequence=["Reconnaissance - identify suppliers and invoice cycles", "Initial contact - spoofed or compromised mailbox", "Manipulation - bank-detail change", "Impact - fraudulent transfer", "Detection - supplier non-payment complaint", "Business impact - financial loss"],
  consequences={"Confidentiality/privacy": "Low.", "Integrity": "Vendor master data altered.", "Availability": "None.", "Operations": "Supplier relationship strain.", "Financial": "Direct loss, often unrecoverable.", "Regulatory": "Low.", "Reputation": "Low to moderate.", "Safety": "None."},
  params={"PbA": P(0.65, "Likely", "BEC is among the most frequent fraud types; billing staff already targeted.", "E6", "Medium"),
          "Pbx": P(0.40, "Moderate", "Verification procedures unknown.", "E1", "Low"),
          "De": P(0.35, "Moderate", "One diverted payment.", "E1", "Medium"),
          "Dm": P(0.60, "Material", "Several large payments diverted.", "E3", "Low"),
          "Th": P(0.45, "Moderate", "Bank recall possible if detected quickly.", "E1", "Low"),
          "Mu": P(0.55, "Moderate", "Financial, not clinical, process.", "E1", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:N/VI:L/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Limited applicability: payment fraud is a process weakness. Representative weakness: spoofable sender domain without enforced DMARC. UI:A staff must act on the instruction; VI:L data changed. The low score understates business impact - rely on damage estimates.",
  red_p=0.80, red_i=0.60, inits=["I12", "I16"],
  treatment="Mandatory call-back verification on bank-detail changes and dual approval above threshold, DMARC enforcement, BEC detection (I16); finance-specific awareness (I12).",
  owner="Finance lead (CFO)", horizon="0-3 months")

S(id="S15", ref="Annex B #7", name="Lost or stolen tablet or handheld exposes patient data",
  statement="A clinician's tablet or handheld used for EHR access is lost or stolen; because device encryption, screen lock and remote wipe are not centrally enforced, patient data cached on the device or accessible through saved sessions is exposed.",
  stakeholders="Clinicians; clinic managers; Privacy officer; IT support; patients.",
  background="Workstations, tablets and handheld devices support EHR access (E2). Encrypted storage is documented for central stores, not for mobile devices; mobile device management is not evidenced.",
  threat_source="Opportunistic thief; accidental loss.", threat_event="Physical loss of a device with data or live sessions.",
  vulns=["MDM, device encryption and remote wipe not evidenced", "Persistent EHR sessions on mobile devices (Analyst assumption)", "Loss-reporting procedure unknown"],
  assets="Mobile endpoints; CJ1 EHR data cached or accessible.", processes="Point-of-care documentation.",
  controls=["Encrypted central storage (E2)"],
  narrative="A tablet is stolen from a car. It has no enforced PIN and holds downloaded referral letters; the EHR app remains logged in. Loss is reported two days later.",
  sequence=["Loss or theft of device", "Access - no lock or weak PIN", "Collection - cached files and active sessions", "Detection - staff report, often delayed", "Response - account revocation, breach assessment", "Business impact - limited privacy breach"],
  consequences={"Confidentiality/privacy": "Records cached on one device.", "Integrity": "Low.", "Availability": "Device replacement.", "Operations": "Minor.", "Financial": "Low.", "Regulatory": "Breach assessment required; may be reportable.", "Reputation": "Low to moderate.", "Safety": "None."},
  params={"PbA": P(0.70, "Likely", "Across 10 clinics, some device loss each year is near certain.", "E1, E2", "Medium"),
          "Pbx": P(0.30, "Limited", "Some protection may exist but is not evidenced.", "E2", "Low"),
          "De": P(0.25, "Limited", "Small number of records.", "E2", "Medium"),
          "Dm": P(0.55, "Material", "Live EHR session allows wider access.", "E2", "Low"),
          "Th": P(0.45, "Moderate", "Accounts can be revoked centrally.", "E2", "Low"),
          "Mu": P(0.60, "Moderate", "Supports but is not essential to care.", "E2", "Medium")},
  cvss="CVSS:4.0/AV:P/AC:L/AT:N/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Representative weakness: missing encryption of sensitive data at rest on the device (CWE-311). AV:P physical possession required; confidentiality only.",
  red_p=0.75, red_i=0.80, inits=["I17"],
  treatment="MDM with enforced encryption, PIN, session timeout, remote wipe and loss-reporting workflow (I17).",
  owner="CIO (Support)", horizon="3-9 months")

S(id="S16", ref="Annex B #5, #49", name="Loss of the Montreal hub or WAN isolates clinics from central clinical systems",
  statement="A carrier failure, cyberattack on network devices or data-centre incident takes the Montreal hub or WAN offline; because clinics depend on a single hub without tested redundancy or local fallback, EHR, imaging, lab and pharmacy access is lost at all ten clinics simultaneously.",
  stakeholders="CIO; Infrastructure; Clinical Ops; clinic managers; telecom carriers; Executive leadership.",
  background="All clinics connect via WAN to the primary hub in Montreal where the main data centre is located (E2). Redundancy, alternate site and failover testing are not documented; data-centre outage was screened out in the 10-scenario assessment and is now included as a resilience scenario.",
  threat_source="Accidental/environmental event, carrier failure, or attacker targeting network infrastructure.",
  threat_event="Enterprise-wide loss of connectivity or hosting.",
  vulns=["Single hub and possibly single carrier (Analyst assumption)", "Firewall redundancy unknown (Annex B #5)", "No alternate processing site evidenced", "Clinic downtime procedures untested (E7)"],
  assets="CJ6 data centre and WAN; all crown jewels dependent on them.", processes="All clinical and administrative services.",
  controls=["High-speed fibre links (E2)", "Off-site backups (E2 - restore time unknown)"],
  narrative="A fibre cut and simultaneous failure of the primary firewall pair leave all clinics without EHR for 14 hours. Clinics switch to paper, cannot view prior imaging or medication history, and postpone non-urgent appointments.",
  sequence=["Trigger - carrier cut, device failure or attack on edge devices", "Impact - WAN/hub unavailable", "Detection - immediate", "Response - carrier escalation, manual workarounds", "Recovery - hours to days", "Business impact - network-wide clinical disruption"],
  consequences={"Confidentiality/privacy": "None.", "Integrity": "Paper records to reconcile afterwards.", "Availability": "All central systems unreachable.", "Operations": "Network-wide degraded care.", "Financial": "Lost activity, overtime.", "Regulatory": "Continuity obligations.", "Reputation": "Moderate.", "Safety": "Missing history at point of care."},
  params={"PbA": P(0.35, "Plausible", "Multi-hour outages of a single hub occur over a 12-month horizon.", "E2", "Low"),
          "Pbx": P(0.50, "Plausible", "Redundancy not evidenced.", "E2", "Low"),
          "De": P(0.55, "Material", "Hours of network-wide outage.", "E1", "Medium"),
          "Dm": P(0.85, "Severe", "Multi-day loss of the hub.", "E2", "Medium"),
          "Th": P(0.35, "Weak", "No alternate site or tested downtime procedures.", "E7", "Medium"),
          "Mu": P(0.95, "Mission-critical", "Hub serves every clinic.", "E2", "High")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:H",
  cvss_note="Limited applicability: architectural dependency, largely non-malicious. Representative weakness: denial of service against a single edge device with no redundancy (AT:P specific conditions); VA:H and SA:H for downstream systems.",
  red_p=0.70, red_i=0.65, inits=["I11", "I18"],
  treatment="Dual carriers / SD-WAN, firewall high availability, cloud or secondary-site failover for EHR read access (I18); tested clinic downtime procedures (I11).",
  owner="CIO (Infrastructure) with Clinical Ops", horizon="6-24 months")

S(id="S17", ref="Annex B #55, #111", name="Unmanaged patient data on local clinic storage is exposed or lost",
  statement="Patient exports, scanned documents and imaging copies accumulate on local clinic storage units outside central access control, retention and monitoring; an insider, intruder or misconfigured share exposes them, or they are lost without backup.",
  stakeholders="Clinic managers; Privacy officer; CIO; Infrastructure; patients.",
  background="Local clinic storage units exist alongside the central data centre (E2); students are asked where copies, exports and local records are stored (E4). Backup jobs for clinic storage have failed in the exercise (E6).",
  threat_source="Curious or malicious insider; intruder; accidental misconfiguration.", threat_event="Unauthorized access to or loss of locally stored data.",
  vulns=["Data sprawl without inventory (E4)", "Permissive share permissions (Analyst assumption)", "Retention schedule not evidenced", "Local backup reliability questionable (E6)"],
  assets="Local clinic storage; copies of CJ1/CJ2 data.", processes="Clinic administration, referrals, scanning.",
  controls=["Encrypted storage (E2)", "On-site and off-site backups (E2)"],
  narrative="A shared folder 'Scans' on a clinic storage unit is readable by all domain users and contains eight years of referral letters. A compromised account indexes it; separately, a disk failure destroys files that were never backed up.",
  sequence=["Condition - data accumulated locally", "Access - broad share permissions or compromised account", "Collection - bulk copy", "Detection - rarely", "Business impact - privacy breach or data loss"],
  consequences={"Confidentiality/privacy": "Years of local records exposed.", "Integrity": "Unverified duplicate records.", "Availability": "Loss of locally held data.", "Operations": "Clean-up effort.", "Financial": "Notification costs.", "Regulatory": "Retention and safeguarding obligations.", "Reputation": "Moderate.", "Safety": "Low."},
  params={"PbA": P(0.45, "Plausible", "Local storage in 10 clinics; insiders and intruders both relevant.", "E2, E4", "Low"),
          "Pbx": P(0.45, "Plausible", "Access controls and inventory unknown.", "E4", "Low"),
          "De": P(0.40, "Moderate", "One clinic's local data.", "E2", "Medium"),
          "Dm": P(0.70, "Severe", "Multiple clinics' historical data.", "E2", "Low"),
          "Th": P(0.40, "Limited", "No monitoring of local storage.", "E4", "Low"),
          "Mu": P(0.65, "Moderate-high", "Supports clinic operations.", "E2", "Medium")},
  cvss="CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:N/VC:H/VI:L/VA:L/SC:N/SI:N/SA:N",
  cvss_note="Representative weakness: incorrect default permissions on network shares (CWE-276). AV:A clinic network; PR:L any domain user.",
  red_p=0.70, red_i=0.70, inits=["I17", "I19"],
  treatment="Data discovery, consolidation of local data into managed central stores, least-privilege shares, retention schedule (I19); encrypted and managed endpoints/storage (I17).",
  owner="Privacy officer with CIO", horizon="3-12 months")

S(id="S18", ref="Annex B #171, #83", name="Web application flaw in the patient portal exposes other patients' records",
  statement="An attacker, or a curious patient, exploits an authorization flaw (insecure direct object reference) or injection weakness in MediBec's online records-access or booking application, retrieving other patients' records at scale.",
  stakeholders="Application owner; development team or vendor; Privacy officer; CIO; patients.",
  background="Online services are used for appointments, records access and communications (E8, MED-CYR-10). Secure development and application testing are auditable areas (E7); no penetration testing is documented.",
  threat_source="External attacker or curious authenticated patient.", threat_event="Exploitation of an application-layer flaw.",
  vulns=["No application penetration testing evidenced", "Secure SDLC not evidenced (E7)", "No WAF evidenced", "Application logging for enumeration unknown"],
  assets="CJ3 patient portal; CJ1 EHR data exposed through it.", processes="Patient records access, booking.",
  controls=["Firewalls, IDS/IPS (E2 - limited for application logic)"],
  narrative="A patient notices the document URL contains a sequential number and changes it, seeing another patient's lab result. A script later downloads 40,000 documents over a weekend.",
  sequence=["Discovery - parameter manipulation", "Exploitation - IDOR / injection", "Collection - scripted enumeration", "Exfiltration - bulk download", "Detection - complaint or social media post", "Business impact - large privacy breach"],
  consequences={"Confidentiality/privacy": "Records of many patients.", "Integrity": "Possible if write functions affected.", "Availability": "Portal taken offline.", "Operations": "Patient contact volume.", "Financial": "Notification and remediation.", "Regulatory": "High.", "Reputation": "High - public-facing.", "Safety": "Low."},
  params={"PbA": P(0.50, "Plausible", "Public applications are constantly probed.", "E8", "Low"),
          "Pbx": P(0.35, "Moderate", "Flaw presence unknown; no testing evidence.", "E7", "Low"),
          "De": P(0.50, "Material", "Partial enumeration before detection.", "E8", "Medium"),
          "Dm": P(0.85, "Severe", "Full patient document store.", "E1", "Medium"),
          "Th": P(0.40, "Limited", "Application monitoring unknown.", "E7", "Low"),
          "Mu": P(0.75, "High", "Patient-facing and trust-critical.", "E8", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:N/VC:H/VI:L/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Representative weakness: authorization bypass through user-controlled key (CWE-639). PR:L any patient account; VC:H cross-patient data.",
  red_p=0.80, red_i=0.60, inits=["I03", "I05", "I14", "I15"],
  treatment="Annual application penetration testing and secure SDLC (I14), WAF with rate limiting (I15), scanning of web tier (I05), enumeration detection (I03).",
  owner="CIO (Application owner)", horizon="3-9 months")

S(id="S19", ref="Annex B #40, #99", name="Trojanized software update from a clinical or IT software supplier",
  statement="A threat actor compromises the build or update infrastructure of software used by MediBec (EHR component, imaging viewer, remote-management tool) and distributes a signed malicious update, which MediBec installs automatically, giving the actor a foothold across many systems at once.",
  stakeholders="CIO; Cybersecurity lead; Procurement; affected supplier; Clinical Ops.",
  background="MediBec runs many vendor applications (E2). Supply-chain verification is not evidenced (E7). Unlike S9 (vendor remote access), this path uses the software itself.",
  threat_source="State-linked or advanced criminal supply-chain actor.", threat_event="Installation of a malicious signed update.",
  vulns=["Automatic updates without staging (Analyst assumption)", "No software bill of materials or supplier assurance (E7)", "Limited egress filtering from servers (Analyst assumption)"],
  assets="Servers and endpoints running the affected software; CJ1, CJ2.", processes="Any process relying on the affected product.",
  controls=["Antimalware (E2 - signed updates usually bypass it)", "EDR (E6)"],
  narrative="A widely used remote-monitoring agent receives a malicious update. It installs on 300 MediBec endpoints and servers within hours and beacons to attacker infrastructure. The supplier discloses the compromise a week later.",
  sequence=["Initial access - malicious signed update", "Execution - on all hosts with the product", "Persistence - legitimate agent", "Discovery and collection", "Detection - supplier or government advisory", "Business impact - enterprise-wide rebuild"],
  consequences={"Confidentiality/privacy": "Broad potential access.", "Integrity": "Trust in all affected hosts lost.", "Availability": "Mass reimaging.", "Operations": "Severe.", "Financial": "High remediation cost.", "Regulatory": "Breach assessment across all systems.", "Reputation": "Moderate (shared with many victims).", "Safety": "Indirect."},
  params={"PbA": P(0.25, "Unlikely-plausible", "Rare but high-impact events.", "E7", "Low"),
          "Pbx": P(0.50, "Plausible", "Signed updates bypass most customer controls.", "E7", "Low"),
          "De": P(0.60, "Major", "Foothold on many hosts.", "E2", "Low"),
          "Dm": P(0.95, "Extreme", "Enterprise-wide compromise.", "E2", "Medium"),
          "Th": P(0.35, "Weak", "Detection depends on external advisories.", "E3", "Medium"),
          "Mu": P(0.85, "Very high", "May affect crown-jewel software.", "E2", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H",
  cvss_note="Limited applicability: supplier compromise. Representative weakness: download of code without integrity check (CWE-494). AC:H and AT:P - the supplier's pipeline must be compromised first.",
  red_p=0.40, red_i=0.65, inits=["I03", "I10", "I11"],
  treatment="Supplier assurance and staged updates for critical software (I10); egress control and behavioural detection (I03); rebuild playbook (I11). Prevention is largely outside MediBec's control - transfer and acceptance required.",
  owner="CIO with Procurement", horizon="3-12 months")

S(id="S20", ref="Annex B #29, #144", name="Takeover of cloud tenant administration through token theft or malicious app consent",
  statement="An attacker steals a session token or tricks a cloud administrator into granting consent to a malicious application, obtaining persistent control of MediBec's cloud tenant, from which they read mail and files, create backdoor accounts and disable logging.",
  stakeholders="CIO; Cybersecurity lead; cloud administrators; cloud provider; Privacy officer.",
  background="Cloud integration supports remote access and data retrieval (E2); cloud configuration, identity and logging are open questions (E4). Push MFA does not stop token theft (E6).",
  threat_source="Cybercriminal or state-linked actor.", threat_event="Compromise of the cloud control plane.",
  vulns=["Token-theft-resistant controls (device binding, conditional access) not evidenced", "Users can consent to third-party apps (Analyst assumption)", "Cloud admin roles not separated or JIT (E7)", "Cloud audit logs not centralised (E4)"],
  assets="CJ5 cloud identity; CJ7 cloud storage; mail and collaboration.", processes="Remote work, communications, image sharing.",
  controls=["MFA push (E6)", "Cloud identity (E2)"],
  narrative="An adversary-in-the-middle phishing kit captures a cloud admin's session cookie, bypassing MFA. The attacker registers an application with mail and file read permissions, adds a global admin and turns off audit retention.",
  sequence=["Initial access - token theft or consent phishing", "Persistence - malicious app, backdoor admin", "Defense evasion - logging disabled", "Collection - mail, files, images", "Exfiltration - via API", "Detection - late", "Business impact - broad breach, tenant rebuild"],
  consequences={"Confidentiality/privacy": "Mail and cloud files containing PHI.", "Integrity": "Tenant configuration altered.", "Availability": "Possible lock-out.", "Operations": "Tenant recovery.", "Financial": "High.", "Regulatory": "High.", "Reputation": "High.", "Safety": "Indirect."},
  params={"PbA": P(0.55, "Plausible", "AiTM kits and consent phishing are widespread.", "E4", "Low"),
          "Pbx": P(0.40, "Moderate", "Push MFA and no conditional access.", "E6", "Low"),
          "De": P(0.55, "Material", "Partial tenant data access.", "E2", "Medium"),
          "Dm": P(0.90, "Extreme", "Full tenant takeover.", "E2", "Medium"),
          "Th": P(0.40, "Limited", "Cloud logging uncertain.", "E4", "Low"),
          "Mu": P(0.85, "Very high", "Cloud identity underpins remote access.", "E2", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H",
  cvss_note="Representative weakness: session token not bound to device, reusable after MFA (CWE-294-type). UI:A admin must interact with the lure; all impacts High because the control plane governs subsequent systems.",
  red_p=0.80, red_i=0.65, inits=["I01", "I02", "I03", "I08"],
  treatment="Phishing-resistant MFA and token-binding conditional access (I01), JIT cloud admin roles and admin-consent workflow (I02), cloud posture baseline (I08), cloud audit logs to MDR (I03).",
  owner="CIO", horizon="0-9 months")

S(id="S21", ref="Annex B #14, #54", name="Accidental disclosure of patient information by staff",
  statement="A staff member unintentionally discloses patient information - misdirected e-mail or fax, wrong attachment, record uploaded to a personal cloud, or document handed to the wrong patient - because data-handling controls and awareness are limited, resulting in privacy incidents and patient complaints.",
  stakeholders="All clinical and administrative staff; Privacy officer; clinic managers; patients.",
  background="MediBec handles high volumes of health information across 10 clinics (E1). Privacy controls expected (classification, DLP, breach assessment) are listed as areas to assess, not as existing controls (E5, E7).",
  threat_source="Negligent insider (human error).", threat_event="Unintended disclosure.",
  vulns=["No DLP or recipient warnings evidenced", "Role-based privacy training unknown (E7)", "Use of fax/e-mail for referrals (Analyst assumption)"],
  assets="CJ1, CJ2 information in transit and in documents.", processes="Referrals, results communication, administration.",
  controls=["Privacy and compliance function (E4 in s.4)"],
  narrative="A clerk sends a batch of lab results to an outside clinic with a similar name selected by e-mail auto-complete. The recipient reports it three days later.",
  sequence=["Error - misdirected transmission", "Exposure - recipient receives data", "Detection - recipient or patient report", "Response - recall request, breach assessment", "Business impact - individual privacy incident"],
  consequences={"Confidentiality/privacy": "Limited number of patients.", "Integrity": "None.", "Availability": "None.", "Operations": "Incident handling workload.", "Financial": "Low.", "Regulatory": "Incident register; notification if risk of serious injury.", "Reputation": "Low to moderate.", "Safety": "Low."},
  params={"PbA": P(0.85, "Very likely", "Human error is near certain across 10 clinics in 12 months.", "E1", "Medium"),
          "Pbx": P(0.50, "Plausible", "Few technical safeguards evidenced.", "E7", "Low"),
          "De": P(0.20, "Minor", "Single patient or small batch.", "E1", "Medium"),
          "Dm": P(0.45, "Moderate", "Large batch sent externally.", "E1", "Low"),
          "Th": P(0.45, "Moderate", "Privacy function exists to respond.", "E4", "Low"),
          "Mu": P(0.60, "Moderate", "Routine communication processes.", "E1", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:A/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Limited applicability: human error. Representative weakness: absence of outbound data-loss safeguards for an authenticated user. The score is low by design; business impact is captured in damage estimates.",
  red_p=0.60, red_i=0.55, inits=["I09", "I12", "I19"],
  treatment="Outbound DLP and recipient warnings (I09), secure referral channel replacing fax/e-mail and data minimization (I19), role-based privacy training (I12).",
  owner="Privacy officer", horizon="3-12 months")

S(id="S22", ref="Annex B #146, #105, #173", name="Interception or exposure of teleconsultations and clinical messaging",
  statement="An outsider joins or records a teleconsultation through an open meeting link, or intercepts clinical messages sent through unapproved or poorly configured communication tools, exposing sensitive consultations.",
  stakeholders="Clinicians; patients; Communications systems owner; Privacy officer; communications vendor.",
  background="Voice, video and messaging services connect clinics and clinicians; confidentiality and secure collaboration are flagged for assessment (E2).",
  threat_source="Opportunistic intruder; curious third party.", threat_event="Unauthorized access to real-time communications.",
  vulns=["Meeting links without waiting room or authentication (Analyst assumption)", "Use of consumer messaging apps by clinicians (Analyst assumption)", "Communication platform configuration baseline not evidenced"],
  assets="Communication systems; consultation content.", processes="Teleconsultation, clinician collaboration.",
  controls=["Communication systems in place (E2 - security settings unknown)"],
  narrative="A recurring meeting link for psychiatry teleconsultations is shared in a patient e-mail and forwarded; an unknown participant joins silently. Separately, clinicians share images through a consumer messaging app.",
  sequence=["Access - reuse of static link or unapproved channel", "Collection - listening or recording", "Detection - participant noticed or not at all", "Business impact - sensitive disclosure"],
  consequences={"Confidentiality/privacy": "Highly sensitive consultations.", "Integrity": "Low.", "Availability": "Low.", "Operations": "Platform reconfiguration.", "Financial": "Low.", "Regulatory": "Moderate.", "Reputation": "Moderate to high for sensitive specialties.", "Safety": "Low."},
  params={"PbA": P(0.35, "Plausible", "Opportunistic; depends on telehealth volume (Evidence gap).", "E2", "Low"),
          "Pbx": P(0.35, "Moderate", "Configuration unknown.", "E2", "Low"),
          "De": P(0.30, "Limited", "Individual consultations.", "E2", "Medium"),
          "Dm": P(0.55, "Material", "Systematic interception.", "E2", "Low"),
          "Th": P(0.45, "Moderate", "Platform controls available if configured.", "E2", "Low"),
          "Mu": P(0.60, "Moderate", "Supports but is not core to most care.", "E2", "Low")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Representative weakness: missing authentication for a meeting resource (CWE-306). AT:P attacker must obtain the link.",
  red_p=0.75, red_i=0.60, inits=["I22"],
  treatment="Approved telehealth and messaging platform with authenticated entry, waiting rooms, encryption and configuration baseline; ban on consumer apps for PHI (I22).",
  owner="Clinical Ops with CIO", horizon="3-6 months")

S(id="S23", ref="Annex B #82, #90, #22", name="Brute force or credential stuffing against exposed administrative interfaces",
  statement="An attacker finds management interfaces (remote desktop, hypervisor or firewall consoles, storage or out-of-band management) exposed to the internet or partner networks and gains access by credential stuffing or default passwords, obtaining administrative control of infrastructure.",
  stakeholders="Infrastructure team; Cybersecurity lead; CIO; managed service providers.",
  background="Exposure of services and inventory completeness are open questions (E4); remote access exists (E2). Exposed admin portals and remote management interfaces appear in the extended catalogue (E8).",
  threat_source="Cybercriminal / initial-access broker.", threat_event="Password attack against an exposed admin interface.",
  vulns=["Unknown internet-exposed services (E4)", "Admin interfaces without MFA (Analyst assumption)", "Default or reused credentials (Analyst assumption)", "No external attack-surface monitoring evidenced"],
  assets="CJ6 infrastructure; hypervisors, firewalls, storage.", processes="All hosted services.",
  controls=["Firewalls (E2)", "IDS/IPS (E2)"],
  narrative="An external scan finds an out-of-band server management port reachable from the internet with the vendor default password. The attacker powers off hosts and later deploys ransomware directly on the hypervisor.",
  sequence=["Discovery - internet scanning", "Initial access - default or stuffed credentials", "Privilege - full admin on device", "Impact - disruption, encryption or data access", "Detection - outage", "Business impact - multi-system outage"],
  consequences={"Confidentiality/privacy": "Access to hosted data.", "Integrity": "Configuration tampering.", "Availability": "Multi-system outage.", "Operations": "Severe.", "Financial": "High.", "Regulatory": "Moderate to high.", "Reputation": "High.", "Safety": "Indirect."},
  params={"PbA": P(0.70, "Likely", "Continuous internet scanning and password attacks.", "E4", "Medium"),
          "Pbx": P(0.35, "Moderate", "Depends on actual exposure - unknown.", "E4", "Low"),
          "De": P(0.60, "Major", "Control of one infrastructure component.", "E2", "Medium"),
          "Dm": P(0.90, "Extreme", "Hypervisor-level ransomware.", "E2", "Medium"),
          "Th": P(0.40, "Limited", "No attack-surface monitoring.", "E4", "Low"),
          "Mu": P(0.85, "Very high", "Infrastructure hosts crown jewels.", "E2", "High")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H",
  cvss_note="Representative weakness: exposed management interface with weak or default credentials (CWE-1392/521). AT:P - success depends on a guessable credential.",
  red_p=0.85, red_i=0.65, inits=["I01", "I02", "I03", "I05"],
  treatment="External attack-surface management and removal of exposed interfaces (I05), MFA and PAM-brokered admin access (I01, I02), monitoring of admin logins (I03).",
  owner="CIO (Infrastructure)", horizon="0-6 months")

S(id="S24", ref="Annex B #168", name="Malware introduced through patient-supplied imaging media or USB devices",
  statement="Malware on a patient-supplied imaging CD/USB or a staff USB drive executes on a radiology workstation or device console when the media is loaded, infecting systems that are poorly protected by endpoint security and connected to the clinical network.",
  stakeholders="Radiology staff; Biomedical engineering; clinic managers; Cybersecurity lead.",
  background="Radiology and interconnected medical equipment are part of the environment (E1, E2); device inventories and endpoint coverage are uncertain (E4). Imaging departments routinely import external media.",
  threat_source="Commodity malware (often unintentional carriers).", threat_event="Execution of malware from removable media.",
  vulns=["Autorun or unrestricted media import on imaging workstations (Analyst assumption)", "Device consoles without EDR (E4)", "No kiosk for media scanning evidenced"],
  assets="CJ2 imaging workstations; CJ8 devices.", processes="Image import for diagnosis and referral.",
  controls=["Antimalware (E2 - coverage of device consoles unknown)"],
  narrative="A patient brings imaging from an outside clinic on a USB key infected with a worm. The import station, running an unsupported OS without EDR, is infected and spreads to a neighbouring modality console.",
  sequence=["Initial access - removable media", "Execution - on import workstation", "Lateral movement - to device consoles", "Disruption - devices unstable", "Detection - device malfunction", "Business impact - imaging downtime"],
  consequences={"Confidentiality/privacy": "Low to moderate.", "Integrity": "Possible image corruption.", "Availability": "Imaging downtime.", "Operations": "Rescheduled exams.", "Financial": "Device vendor remediation.", "Regulatory": "Low.", "Reputation": "Low.", "Safety": "Delayed diagnostics."},
  params={"PbA": P(0.35, "Plausible", "External media is imported routinely.", "E2", "Low"),
          "Pbx": P(0.40, "Moderate", "Endpoint coverage of device consoles unknown.", "E4", "Low"),
          "De": P(0.45, "Moderate", "One imaging area disrupted.", "E2", "Medium"),
          "Dm": P(0.80, "Severe", "Spread to multiple devices.", "E4", "Low"),
          "Th": P(0.40, "Limited", "No device monitoring.", "E4", "Low"),
          "Mu": P(0.80, "Very high", "Imaging is a core diagnostic service.", "E1", "Medium")},
  cvss="CVSS:4.0/AV:P/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:L/SI:L/SA:L",
  cvss_note="Representative weakness: automatic execution of content from removable media. AV:P media inserted physically; UI:P staff loads it.",
  red_p=0.75, red_i=0.65, inits=["I03", "I06", "I07", "I12"],
  treatment="Media-scanning kiosk and device control, EDR where supported (I03), medical device hardening (I07), isolating imaging segments (I06), staff procedure (I12).",
  owner="Radiology lead with Cybersecurity lead", horizon="3-12 months")

S(id="S25", ref="Annex B #132, #138", name="Retired devices or medical equipment released with recoverable patient data",
  statement="Workstations, drives, printers, storage units or medical equipment are returned to lessors, sold or recycled without certified data sanitization, and a third party recovers patient data from them.",
  stakeholders="Infrastructure; Biomedical engineering; Procurement; Privacy officer; disposal vendor.",
  background="MediBec operates many endpoints, local storage units and devices that store images (E2). Asset lifecycle and disposal controls are not documented.",
  threat_source="Downstream buyer, recycler or researcher.", threat_event="Recovery of data from disposed media.",
  vulns=["No certified sanitization process evidenced", "Leased device return process (Analyst assumption)", "Asset inventory incomplete (E4)"],
  assets="Retired endpoints, storage and medical equipment.", processes="Asset disposal, lease returns.",
  controls=["Encrypted storage for central data (E2 - not necessarily device drives)"],
  narrative="An ultrasound unit returned at lease end still holds 3,000 studies. It is resold; the buyer finds the data and contacts the media.",
  sequence=["Disposal without sanitization", "Transfer to third party", "Recovery of data", "Disclosure or report", "Business impact - privacy breach"],
  consequences={"Confidentiality/privacy": "Historical records on the device.", "Integrity": "None.", "Availability": "None.", "Operations": "Retrieval effort.", "Financial": "Notification costs.", "Regulatory": "Safeguarding obligations.", "Reputation": "Moderate to high if media involved.", "Safety": "None."},
  params={"PbA": P(0.40, "Plausible", "Disposals occur every year.", "E2", "Low"),
          "Pbx": P(0.35, "Moderate", "Sanitization practice unknown.", "E2", "Low"),
          "De": P(0.35, "Moderate", "One device's data.", "E2", "Medium"),
          "Dm": P(0.65, "Material", "Batch of storage units.", "E2", "Low"),
          "Th": P(0.45, "Moderate", "Contracts may impose vendor wiping (unknown).", "E2", "Low"),
          "Mu": P(0.55, "Moderate", "Lifecycle process.", "E2", "Low")},
  cvss="CVSS:4.0/AV:P/AC:L/AT:N/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Representative weakness: sensitive information in resource not removed before reuse (CWE-226). AV:P physical possession.",
  red_p=0.85, red_i=0.60, inits=["I17", "I19"],
  treatment="Certified sanitization with certificates of destruction, lease-return clauses, full-disk encryption on all devices (I17, I19).",
  owner="CIO with Biomedical engineering", horizon="0-6 months")

S(id="S26", ref="Annex B #141", name="Staff paste patient data into unapproved generative-AI tools",
  statement="Clinicians and administrative staff use public generative-AI tools to summarize notes, draft letters or translate documents, pasting identifiable patient information into services whose data retention, training use and location MediBec has not assessed, resulting in uncontrolled disclosure of health information.",
  stakeholders="Clinicians; administrative staff; Privacy officer; CIO; Legal; AI service providers.",
  background="Health information is highly sensitive (E1) and privacy controls are a priority in the appetite statement (E5). No AI acceptable-use policy or approved tool is documented.",
  threat_source="Well-intentioned insider; AI service provider handling.", threat_event="Transfer of personal health information to an unapproved third party.",
  vulns=["No AI acceptable-use policy evidenced", "No approved alternative tool", "Web DLP / category controls not evidenced", "Awareness content does not cover AI (Analyst assumption)"],
  assets="CJ1 clinical notes and letters.", processes="Documentation, correspondence, translation.",
  controls=["Privacy and compliance function (s.4)"],
  narrative="Clinicians use a free chatbot to turn dictated notes into referral letters. Over months, thousands of identifiable notes are submitted to a service that retains prompts outside Canada.",
  sequence=["Use - staff submit PHI to external AI", "Exposure - data retained by provider", "Detection - audit or complaint", "Response - privacy assessment", "Business impact - systemic privacy non-compliance"],
  consequences={"Confidentiality/privacy": "Systemic uncontrolled transfer.", "Integrity": "AI-generated errors in records.", "Availability": "None.", "Operations": "Policy change and retraining.", "Financial": "Legal costs.", "Regulatory": "Cross-border transfer and consent issues (counsel to confirm).", "Reputation": "Moderate to high.", "Safety": "Possible clinical errors from unchecked AI output."},
  params={"PbA": P(0.80, "Very likely", "Generative-AI use among clinicians is widespread by 2026.", "E1", "Medium"),
          "Pbx": P(0.55, "Moderate-high", "No policy or technical controls evidenced.", "E5", "Low"),
          "De": P(0.35, "Moderate", "Limited volume, low misuse likelihood.", "E1", "Low"),
          "Dm": P(0.65, "Material", "Systemic transfer plus clinical errors.", "E5", "Low"),
          "Th": P(0.40, "Limited", "No visibility of AI use.", "E5", "Low"),
          "Mu": P(0.70, "High", "Clinical documentation.", "E1", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Limited applicability: policy and data-governance gap. Representative weakness: exposure of sensitive information to an unauthorized actor via unrestricted egress (CWE-200). AT:P - harm depends on provider retention.",
  red_p=0.65, red_i=0.55, inits=["I09", "I12", "I20"],
  treatment="AI acceptable-use policy, sanctioned privacy-assessed AI tool, web category controls and DLP for AI sites (I20, I09), training (I12).",
  owner="Privacy officer with CMO", horizon="0-6 months")

S(id="S27", ref="Annex B #96 (social engineering)", name="Help-desk impersonation leads to MFA reset and account takeover",
  statement="An attacker phones the IT help desk impersonating a clinician or manager, uses publicly available details to pass weak identity checks, and has the password and MFA device reset, taking over the account and accessing EHR and remote access.",
  stakeholders="IT support/help desk; Cybersecurity lead; clinicians; CIO.",
  background="IT support is part of the 15-person IT team (E3). Help-desk identity verification is not documented. Remote access relies on MFA push (E6), which a reset defeats.",
  threat_source="Social-engineering-capable cybercriminal group.", threat_event="Fraudulent credential and MFA reset.",
  vulns=["Help-desk verification based on knowable data (Analyst assumption)", "No manager or video verification for MFA resets", "No alerting on MFA device changes (E7)"],
  assets="CJ5 identity; CJ1 EHR.", processes="Account support.",
  controls=["MFA push (E6)"],
  narrative="Posing as a physician travelling to a conference, the caller gives employee number and date of hire found online and asks for an MFA reset. The attacker enrols their own phone and logs in within minutes.",
  sequence=["Reconnaissance - staff details from public sources", "Social engineering - help-desk call", "Account takeover - new MFA enrolled", "Access - EHR and remote access", "Escalation - toward S2 or data theft", "Detection - legitimate user locked out", "Business impact - breach or intrusion"],
  consequences={"Confidentiality/privacy": "EHR access under a clinician identity.", "Integrity": "Possible record changes.", "Availability": "User lockout.", "Operations": "Help-desk process change.", "Financial": "Moderate.", "Regulatory": "Reportable if data accessed.", "Reputation": "Moderate.", "Safety": "Indirect."},
  params={"PbA": P(0.55, "Plausible", "Help-desk social engineering is an active technique against healthcare.", "E4", "Low"),
          "Pbx": P(0.50, "Plausible", "Verification procedures unknown.", "E3", "Low"),
          "De": P(0.55, "Material", "One account's reach.", "E6", "Medium"),
          "Dm": P(0.90, "Extreme", "Privileged account leads to enterprise compromise.", "E1", "Medium"),
          "Th": P(0.40, "Limited", "MFA change not monitored.", "E7", "Low"),
          "Mu": P(0.85, "Very high", "Identity gateway.", "E2", "High")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:H/VI:H/VA:L/SC:H/SI:L/SA:L",
  cvss_note="Limited applicability: process weakness. Representative weakness: weak authentication of the account-recovery process (CWE-640). UI:A help-desk agent acts.",
  red_p=0.80, red_i=0.60, inits=["I01", "I12", "I21"],
  treatment="Strong help-desk verification (call-back, manager approval, video ID) for resets (I21), phishing-resistant authenticators that cannot be re-enrolled by phone (I01), alerts on MFA changes and awareness (I12).",
  owner="CIO (Support)", horizon="0-3 months")

S(id="S28", ref="Annex B #15, #115", name="Malicious or departing IT administrator sabotages systems",
  statement="A disgruntled or departing IT administrator with broad standing privileges deletes backups, disables accounts or plants logic bombs; with a 15-person IT team and concentrated knowledge, MediBec cannot quickly detect or reverse the actions, causing prolonged outages.",
  stakeholders="CIO; HR; Executive leadership; Cybersecurity lead; Legal.",
  background="IT is a lean 15-person team with two security staff (E3). Privileged access management, admin monitoring and separation of duties are not evidenced (E7). Key-person dependency is implicit.",
  threat_source="Malicious privileged insider.", threat_event="Destructive administrative actions.",
  vulns=["Standing domain-admin rights (Analyst assumption)", "No monitoring of admin actions (Annex B #115)", "Weak offboarding of privileged users (Analyst assumption)", "Backups deletable by same admins (see S3)"],
  assets="CJ5, CJ6 and all hosted crown jewels.", processes="All.",
  controls=["Backups (E2)"],
  narrative="An administrator dismissed on a Friday retains VPN access over the weekend, deletes the backup catalogue and schedules a script that wipes several servers on Monday morning.",
  sequence=["Motive - dismissal or grievance", "Access - standing privileges", "Sabotage - deletion, disabling, time-delayed scripts", "Detection - outage", "Response - limited knowledge to rebuild", "Business impact - prolonged outage"],
  consequences={"Confidentiality/privacy": "Possible data theft.", "Integrity": "System configurations destroyed.", "Availability": "Prolonged outage.", "Operations": "Severe.", "Financial": "High.", "Regulatory": "Continuity obligations.", "Reputation": "Moderate.", "Safety": "Delayed care."},
  params={"PbA": P(0.15, "Unlikely", "Malicious privileged insiders are rare.", "E3", "Low"),
          "Pbx": P(0.60, "Likely", "If motivated, broad privileges make success likely.", "E3, E7", "Medium"),
          "De": P(0.60, "Major", "Several systems destroyed.", "E2", "Medium"),
          "Dm": P(0.95, "Extreme", "Backups and core systems destroyed.", "E2", "Medium"),
          "Th": P(0.35, "Weak", "Key-person dependency; no admin monitoring.", "E3", "Medium"),
          "Mu": P(0.90, "Very high", "Infrastructure-wide.", "E2", "High")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H",
  cvss_note="Limited applicability: insider abuse of legitimate privileges. Representative weakness: excessive standing privileges (CWE-250). PR:H administrator.",
  red_p=0.55, red_i=0.60, inits=["I02", "I03", "I04", "I11"],
  treatment="PAM with JIT and session recording, separation of duties (I02), monitoring of admin actions (I03), immutable backups outside admin reach (I04), HR-IT offboarding playbook (I11).",
  owner="CIO with HR", horizon="2-12 months")

S(id="S29", ref="Annex B #153, #176", name="Interception or tampering of unencrypted clinical interface traffic (HL7/DICOM)",
  statement="An attacker positioned on the clinic network or WAN captures or alters unencrypted HL7 lab/pharmacy messages or DICOM image transfers between clinical systems, exposing results or injecting false values that flow into the EHR.",
  stakeholders="Laboratory and pharmacy leads; Radiology; integration team; CIO; Cybersecurity lead.",
  background="EHR, radiology, lab and pharmacy systems are integrated (E2); data integrity and application monitoring are to be assessed (E2). Encryption of interface traffic is not documented; legacy clinical protocols are often cleartext.",
  threat_source="Attacker with internal network position (following S2, S7, S12).", threat_event="Man-in-the-middle on clinical interfaces.",
  vulns=["Cleartext HL7/DICOM (Analyst assumption)", "No message integrity validation (Analyst assumption)", "Flat network allowing interception (see S7)"],
  assets="CJ2 lab, pharmacy, imaging interfaces; CJ1 EHR.", processes="Result reporting, medication orders, image transfer.",
  controls=["Firewalls and IDS/IPS (E2)"],
  narrative="An attacker with a foothold in a clinic uses ARP spoofing to intercept lab result messages to the EHR, harvesting results and altering several potassium values.",
  sequence=["Prerequisite - internal foothold", "Interception - ARP/route manipulation", "Collection or manipulation of messages", "Detection - clinical inconsistency", "Business impact - wrong results in the record"],
  consequences={"Confidentiality/privacy": "Results and images exposed.", "Integrity": "False results or orders.", "Availability": "Low.", "Operations": "Result verification.", "Financial": "Moderate.", "Regulatory": "Moderate to high.", "Reputation": "High if harm.", "Safety": "Direct - incorrect results."},
  params={"PbA": P(0.25, "Unlikely-plausible", "Requires internal position and intent.", "E2", "Low"),
          "Pbx": P(0.40, "Moderate", "Cleartext likely; exploitation requires skill.", "E2", "Low"),
          "De": P(0.45, "Moderate", "Some results exposed.", "E2", "Low"),
          "Dm": P(0.85, "Severe", "Altered results lead to harm.", "E5", "Medium"),
          "Th": P(0.40, "Limited", "No integrity checks evidenced.", "E2", "Low"),
          "Mu": P(0.85, "Very high", "Lab and pharmacy data drive treatment.", "E1", "High")},
  cvss="CVSS:4.0/AV:A/AC:L/AT:P/PR:N/UI:N/VC:H/VI:H/VA:N/SC:N/SI:H/SA:N",
  cvss_note="Representative weakness: cleartext transmission of sensitive information (CWE-319) without integrity check (CWE-353). AV:A adjacent; AT:P attacker must be on path; SI:H downstream EHR.",
  red_p=0.75, red_i=0.70, inits=["I06", "I13", "I22"],
  treatment="TLS/VPN for HL7 and DICOM, interface-engine hardening (I22), segmentation (I06), reconciliation of results (I13).",
  owner="CIO (Integration) with Laboratory lead", horizon="6-15 months")

S(id="S30", ref="Appendix A domain; Annex B #65, #71", name="Criminals impersonate MediBec to defraud or phish patients",
  statement="Fraudsters register look-alike domains and send SMS or e-mail messages posing as MediBec (appointment confirmations, billing notices, results available) to harvest patients' credentials, health-card details or payments, harming patients and eroding trust even though MediBec's systems are not breached.",
  stakeholders="Patients; Communications; Privacy officer; Cybersecurity lead; clinic front desks; telecom and domain registrars.",
  background="The exercise phishing used a newly registered look-alike domain (E6, Appendix A). Brand monitoring, DMARC and patient communication standards are not documented.",
  threat_source="Fraud group.", threat_event="Brand impersonation targeting patients.",
  vulns=["No look-alike domain monitoring or takedown (E6)", "DMARC enforcement unknown", "No published patient communication standard (e.g. 'we never ask for...')"],
  assets="Patient trust; CJ3 patient communications.", processes="Patient communications, billing.",
  controls=["None evidenced"],
  narrative="Patients receive texts 'MediBec: your results are ready, confirm identity' linking to a copy of the portal. Hundreds enter credentials and health-card numbers; front desks receive angry calls.",
  sequence=["Preparation - look-alike domain and portal clone", "Campaign - SMS/e-mail to patients", "Harvest - credentials and payment data", "Detection - patient calls", "Response - takedown, warnings", "Business impact - patient harm, trust erosion"],
  consequences={"Confidentiality/privacy": "Patient credentials and identifiers stolen outside MediBec.", "Integrity": "None.", "Availability": "Call volume.", "Operations": "Front-desk load.", "Financial": "Low direct cost.", "Regulatory": "Low to moderate.", "Reputation": "Moderate to high.", "Safety": "Low."},
  params={"PbA": P(0.70, "Likely", "Look-alike domain already observed in the exercise.", "E6", "Medium"),
          "Pbx": P(0.50, "Plausible", "No brand protection evidenced.", "E6", "Low"),
          "De": P(0.30, "Limited", "Some patients defrauded.", "E6", "Low"),
          "Dm": P(0.55, "Material", "Large campaign and portal clone.", "E6", "Low"),
          "Th": P(0.45, "Moderate", "Takedown possible once detected.", "E6", "Low"),
          "Mu": P(0.55, "Moderate", "Trust and patient communications.", "E5", "Medium")},
  cvss="CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N",
  cvss_note="Limited applicability: impersonation outside MediBec's systems. Representative weakness: sender domain spoofable without enforced DMARC. Business impact is captured by damage estimates, not CVSS.",
  red_p=0.55, red_i=0.60, inits=["I12", "I16", "I23"],
  treatment="Look-alike domain monitoring and takedown, verified sender channels, patient communication standard and awareness notices (I23), DMARC enforcement (I16), staff reporting (I12).",
  owner="Communications lead", horizon="0-6 months")

# ---------------------------------------------------------------- new initiatives (scenario lists derived from scenario inits)
NEW_INITS = [
    ("I14", "Application security and secrets management", "Secret scanning in repositories and pipelines, central vault with short-lived credentials, secure SDLC gates, annual penetration test of patient-facing applications.", "CIO (Application development)", "Near-term", 140000, 70000, "Month 3", "Month 9", "0 unresolved exposed secrets; 0 open critical pen-test findings > 30 days", "Repository inventory", "Prevention"),
    ("I15", "DDoS protection, CDN and web application firewall", "Upstream DDoS mitigation, CDN and WAF with rate limiting for public services; separate egress for clinic cloud traffic.", "CIO", "Immediate", 40000, 60000, "Month 1", "Month 4", "Public services protected; DDoS runbook tested", "ISP contract", "Prevention / Resilience"),
    ("I16", "Payment-fraud controls and e-mail authentication", "Call-back verification and dual approval for bank-detail changes; DMARC p=reject; BEC detection rules.", "Finance lead / Cybersecurity lead", "Immediate", 30000, 15000, "Month 0", "Month 3", "100% bank changes verified; DMARC enforced on all domains", "Finance process owner", "Prevention"),
    ("I17", "Mobile device management, encryption and secure disposal", "MDM with enforced encryption, PIN, remote wipe; full-disk encryption on all endpoints and storage; certified sanitization and lease-return process.", "CIO (Support)", "Near-term", 80000, 50000, "Month 2", "Month 9", "100% mobile devices enrolled; 100% disposals certified", "Asset inventory (I05)", "Prevention"),
    ("I18", "Network and hosting resilience", "Dual carriers / SD-WAN to clinics, firewall high availability, cloud or secondary-site read access to EHR, annual failover test.", "CIO (Infrastructure)", "Planned", 350000, 120000, "Month 6", "Month 20", "Clinics maintain EHR read access through a hub failure test", "Architecture review; carrier contracts", "Resilience"),
    ("I19", "Data lifecycle and minimization", "Data discovery on clinic storage, consolidation into managed stores, retention schedule, secure referral channel replacing fax/e-mail.", "Privacy officer / CIO", "Near-term", 120000, 40000, "Month 3", "Month 12", "Local PHI stores reduced by 80%; retention schedule applied", "Data classification", "Governance"),
    ("I20", "Responsible use of generative AI", "AI acceptable-use policy, privacy-assessed sanctioned AI tool, web category controls for public AI, clinician guidance on verifying output.", "Privacy officer / CMO", "Immediate", 60000, 40000, "Month 0", "Month 6", "Approved tool available; blocked PHI uploads to unapproved AI trending down", "Privacy impact assessment", "Governance / Prevention"),
    ("I21", "Help-desk identity verification", "Call-back to directory number, manager approval or video ID for password and MFA resets; alerts on authenticator changes.", "CIO (Support)", "Immediate", 25000, 10000, "Month 0", "Month 2", "100% resets follow verified procedure (sample audit)", "I01", "Prevention"),
    ("I22", "Secure clinical communications and interfaces", "Approved telehealth/messaging platform with authenticated entry; TLS/VPN for HL7 and DICOM; interface-engine hardening.", "CIO (Integration) / Clinical Ops", "Near-term", 110000, 30000, "Month 3", "Month 12", "100% clinical interfaces encrypted; consumer apps retired for PHI", "Vendor support for TLS", "Prevention"),
    ("I23", "Brand protection and patient anti-fraud communication", "Look-alike domain and social monitoring with takedown service; verified sender IDs; patient communication standard and website notices.", "Communications lead", "Immediate", 25000, 30000, "Month 0", "Month 3", "Takedown within 48 h of detection; patient notice published", "I16", "Detection / Response"),
]

NEW_KRIS = [
    ("KRI-13", "Exposed secrets detected / unresolved > 24 h", "S11", "Count from secret scanning", "Repository scanner", "CIO (Dev)", "Monthly", "0 unresolved", ">= 1", ">= 1 with PHI scope"),
    ("KRI-14", "% bank-detail changes verified by call-back; DMARC policy", "S14, S30", "Verified / total; policy state", "Finance workflow, DNS", "Finance lead", "Monthly", "100%; reject", "< 100%; quarantine", "< 90%; none"),
    ("KRI-15", "% mobile devices enrolled and encrypted; certified disposals", "S15, S25", "Enrolled / inventory; certificates / disposals", "MDM, asset register", "CIO (Support)", "Monthly", "100%", "< 95%", "< 85%"),
    ("KRI-16", "Result of hub/WAN failover test (clinic EHR read access)", "S16", "Clinics retaining access during test", "DR test records", "CIO (Infra)", "Annual", "10/10", "< 10", "< 7"),
    ("KRI-17", "Attempts to upload data to unapproved AI services", "S26", "Blocked/alerted events per month", "Web proxy / DLP", "Privacy officer", "Monthly", "Declining trend", "Rising 2 months", "PHI upload confirmed"),
    ("KRI-18", "% help-desk resets passing verification audit", "S27", "Sampled resets compliant / sampled", "Ticketing system", "CIO (Support)", "Monthly", "100%", "< 98%", "< 90%"),
    ("KRI-19", "Open critical/high findings on patient-facing applications", "S18", "Count past 30 days", "Pen-test tracker", "CIO (App owner)", "Monthly", "0", ">= 1", ">= 3"),
    ("KRI-20", "Internet-exposed management interfaces", "S23, S6", "Count from attack-surface monitoring", "EASM tool", "CIO (Infra)", "Weekly", "0", ">= 1", ">= 1 without MFA"),
]

# candidates C21-C45 (C01-C20 carried over with updated decisions)
UPDATED_DECISIONS = {
    "C05": ("Selected (S11)", "Now retained: portfolio of 30 allows coverage of development-related exposure."),
    "C06": ("Selected (S12)", "Now retained as a distinct wireless entry path (S7 remains the device-safety scenario)."),
    "C10": ("Selected (S13)", "Now retained: availability of patient-facing services."),
    "C16": ("Selected (S16)", "Now retained as a resilience scenario (hub concentration)."),
    "C17": ("Selected (S17)", "Now retained: data sprawl on local clinic storage."),
    "C18": ("Selected (S14)", "Now retained: direct financial loss pathway."),
    "C19": ("Selected (S15)", "Now retained: mobile endpoints used for EHR access."),
}
NEW_CANDIDATES = [
    ("C21", "Authorization flaw in patient portal exposes other patients' records", "External actor / patient", "No app testing or WAF", "CJ3 / CJ1", "Bulk record exposure", "Annex B #171", "Selected (S18)", "Public-facing, high privacy impact."),
    ("C22", "Trojanized software update from a supplier", "Supply-chain actor", "Automatic updates, no supplier assurance", "Many hosts", "Enterprise foothold", "Annex B #40", "Selected (S19)", "Distinct from S9 (software path vs. remote-access path)."),
    ("C23", "Cloud tenant takeover via token theft or consent phishing", "Cybercriminal", "Token not device-bound; user consent allowed", "CJ5 / CJ7", "Tenant-wide control", "Annex B #29", "Selected (S20)", "Control-plane risk distinct from S4 storage exposure and S1 clinical accounts."),
    ("C24", "Misdirected e-mail/fax or wrong-patient disclosure", "Negligent insider", "No DLP, manual referrals", "CJ1", "Privacy incident", "Annex B #14", "Selected (S21)", "Most frequent privacy incident type."),
    ("C25", "Teleconsultation or clinical messaging intercepted", "Opportunistic intruder", "Open meeting links, consumer apps", "Communications", "Sensitive disclosure", "Annex B #146", "Selected (S22)", "Communication systems flagged in E2."),
    ("C26", "Exposed admin interfaces attacked with stuffed/default credentials", "Cybercriminal", "Internet-exposed management ports", "CJ6", "Infrastructure takeover", "Annex B #82, #90", "Selected (S23)", "Misconfiguration path distinct from S6 (unpatched)."),
    ("C27", "Malware on patient-supplied imaging media", "Commodity malware", "Media import without scanning", "CJ2 / CJ8", "Imaging downtime", "Annex B #168", "Selected (S24)", "Healthcare-specific entry path."),
    ("C28", "Data left on disposed devices and leased equipment", "Downstream buyer", "No certified sanitization", "Retired assets", "Privacy breach", "Annex B #138", "Selected (S25)", "Lifecycle gap; cheap to fix."),
    ("C29", "Patient data pasted into public generative-AI tools", "Well-intentioned insider", "No AI policy or controls", "CJ1", "Uncontrolled disclosure", "Annex B #141", "Selected (S26)", "Emerging, high-frequency privacy risk."),
    ("C30", "Help-desk vishing leads to MFA reset", "Social engineer", "Weak reset verification", "CJ5", "Account takeover", "Annex B #96", "Selected (S27)", "Bypasses MFA investments in S1; distinct process weakness."),
    ("C31", "Malicious or departing IT admin sabotage", "Privileged insider", "Standing privileges, weak offboarding", "CJ5 / CJ6", "Destructive outage", "Annex B #15", "Selected (S28)", "Low likelihood, extreme impact; key-person dependency."),
    ("C32", "Interception/tampering of HL7/DICOM traffic", "Attacker with internal position", "Cleartext interfaces", "CJ2", "Wrong results", "Annex B #153", "Selected (S29)", "Integrity path distinct from S10 (record-level changes)."),
    ("C33", "Look-alike domains and smishing targeting patients", "Fraud group", "No brand monitoring, DMARC unknown", "Patient trust", "Patient fraud", "Appendix A", "Selected (S30)", "Look-alike domain already observed."),
    ("C34", "Mass encryption of hypervisors", "Ransomware group", "Hypervisor management reachable", "CJ6", "Outage", "Annex B #44", "Merged into S2/S23", "Same outcome as S2; exposure path in S23."),
    ("C35", "Active Directory misconfiguration enables domain takeover", "Any intruder", "No AD audits", "CJ5", "Domain dominance", "Annex B #186", "Merged into S2", "Escalation step within S2 chain; treated by I02."),
    ("C36", "End-of-support workstation operating systems in clinics", "Cybercriminal", "Unsupported OS", "Endpoints", "Exploitation", "Annex B #79", "Merged into S6", "Covered by EOL element of S6 and KRI-04."),
    ("C37", "Cryptomining on cloud or server resources", "Cybercriminal", "Weak cloud controls", "Cloud", "Cost, slowdown", "Annex B #48", "Not selected", "Low consequence for mission."),
    ("C38", "Skimming on online payment page", "Fraudster", "Third-party scripts", "Online payments", "Card theft", "Annex B #63", "Not selected", "Card processing not evidenced; PCI out of scope."),
    ("C39", "Physical intrusion into clinic server closet", "Thief / intruder", "Weak physical controls", "Clinic equipment", "Theft, tampering", "Annex B #121", "Not selected", "Physical security out of scope; partly covered by S15/S17 encryption."),
    ("C40", "Insufficient logs to prove breach scope", "Any incident", "Short retention", "All", "Unprovable scope", "Annex B #140", "Merged into S8", "Same control family (I03)."),
    ("C41", "Clinician mailbox compromise used to harvest PHI", "Cybercriminal", "Push MFA", "Mail", "Breach", "Annex B #33", "Merged into S1/S20", "Same causal chain."),
    ("C42", "AI scribe SaaS mishandles recordings", "Third party", "Unassessed vendor", "CJ1", "Privacy breach", "Annex B #141", "Merged into S26/S9", "Covered by AI governance and vendor risk."),
    ("C43", "Building IoT or CCTV used as foothold", "Cybercriminal", "Unmanaged IoT", "Clinic LAN", "Foothold", "Annex B #43", "Merged into S7", "Same segmentation treatment."),
    ("C44", "Excessive data retention amplifies breach size", "N/A (amplifier)", "No retention schedule", "All data", "Larger breaches", "Annex B #74", "Merged into S17", "Treated by I19."),
    ("C45", "Firewall single point of failure", "Accidental / attacker", "No redundancy", "CJ6", "Outage", "Annex B #5", "Merged into S16", "Same resilience treatment (I18)."),
]
