# -*- coding: utf-8 -*-
"""Scenario-selection data for MediBec under the scenario-selection instructions (Sections A-E)."""
import re
import data30 as M

SC = {s["id"]: s for s in M.SCEN}

# ================================================================ SECTION A
SCOPE = [
    ("Organization", "MediBec private medical centre - Montreal head office and data centre, 10 clinics (Montreal, Quebec City, Gatineau, Saguenay).", "Documented (E1)"),
    ("Scope", "All clinical, administrative and supporting technology services, including cloud, clinic networks, medical equipment, vendors and staff use of external services.", "Analyst definition"),
    ("Time horizon", "12 months (October 2026 - September 2027) for probability estimates.", "Instruction s.1 default"),
    ("Purpose", "Select 10 scenarios representing MediBec's material cyber exposure for detailed CyberRiskGuardian quantification.", "User request"),
    ("Mission", "Deliver high-quality healthcare supported by technology, efficient clinical workflows and secure access to patient information.", "Documented (E1)"),
    ("Strategic context", "2024-2030 cybersecurity roadmap; increasing attack attempts since 2020; no confirmed breach; lean IT (15 staff, 2 in security).", "Documented (E3, E4)"),
    ("Maturity (indicative)", "Perimeter controls (firewalls, IDS/IPS, antimalware), EDR, encrypted storage, on/off-site backups, push MFA on remote access. No evidence of PAM, SIEM/24x7 monitoring, segmentation, immutable backup, vendor risk programme, tested IR.", "Documented (E2) + exercise evidence (E6) + analyst inference"),
    ("Known weaknesses (exercise evidence)", "Macro phishing lure from look-alike domain; PowerShell alert closed as low severity; MFA push approved from unusual geography; external download of medical-image export; unusual queries by ehr-sync-svc; clinic backup failures.", "Exercise evidence (E6) - validate"),
    ("Obligations", "Quebec and Canadian privacy expectations for health information (confidentiality incidents, register, notification where risk of serious injury), professional obligations, contracts with cloud/technology vendors, evidence preservation.", "Documented (s.5) - legal counsel to confirm regime"),
    ("Risk appetite", "Low appetite for patient-safety, health-data, compliance and trust risks; moderate for governed innovation. Case tolerance 0.40 normalized; analyst estimate 0.30 used in CRG calculations. Residual > 0.25 executive review; > 0.40 Board acceptance.", "Documented (E5) + analyst estimate"),
]
OBJECTIVES = [
    ("O1", "Safe, continuous patient care in all 10 clinics", "Clinical documentation, diagnostics, prescribing, appointments"),
    ("O2", "Protection of patient health information and privacy compliance", "EHR access, image sharing, referrals, communications"),
    ("O3", "Operational and financial continuity", "Billing, payments, supplier management, administration"),
    ("O4", "Public and patient trust", "Patient communications, online services, incident communications"),
    ("O5", "Governed modernization (2024-2030)", "Cloud, AI, device and application adoption"),
]
ASSET_MAP = [  # objective, process, primary asset, supporting assets, dependencies, potential consequences
    ("O1", "Clinical documentation and decision-making", "Patient record (EHR data) and its integrity", "EHR application and database, workstations, tablets", "Identity/MFA, Montreal DC, WAN, EHR vendor", "Delayed or unsafe care, clinic disruption"),
    ("O1", "Diagnostics (imaging, lab) and pharmacy", "Diagnostic results, images, medication data", "Imaging modalities, lab/pharmacy systems, HL7/DICOM interfaces", "Medical-device vendors, interface engine, network", "Wrong or delayed diagnosis, medication errors"),
    ("O1", "Appointment and patient flow", "Scheduling service", "Scheduling system, online booking, phones", "Internet link, hosting provider", "Cancelled appointments, overload"),
    ("O2", "Access to and sharing of health information", "Patient health information (all stores)", "Cloud storage, clinic storage units, e-mail, APIs, backups", "Cloud provider, identity, integration partners", "Privacy breach, notification, sanctions"),
    ("O3", "Billing and payments", "Financial assets, billing data", "Billing system, accounts payable, e-mail", "Banks, payers, billing vendor", "Financial loss, cash-flow disruption"),
    ("O3", "IT operations and recovery", "Ability to restore services", "Backup servers, off-site copies, admin tooling", "Backup identity, off-site provider, admin staff", "Prolonged outage, permanent data loss"),
    ("O4", "Patient communications", "MediBec brand and patient trust", "Web site, SMS/e-mail senders, telehealth platform", "DNS, communication vendors", "Loss of trust, patient fraud"),
    ("O5", "Clinical innovation (AI, cloud, devices)", "New digital capabilities", "SaaS/AI tools, cloud services, new devices", "External AI and SaaS providers", "Uncontrolled data transfer, new attack surface"),
]
DEPENDENCIES = [  # dependency, type, what depends on it, SPOF/concentration, peripheral?, related candidates
    ("Directory, MFA and cloud identity", "Identity", "Every crown jewel; remote and cloud access", "Concentration - single identity plane; push MFA", "No", "C01, C20, C23, C30, C35, C41"),
    ("Montreal data centre and WAN hub", "Location / network", "EHR, identity, backups, imaging for all 10 clinics", "Single point of failure (no alternate site evidenced)", "No", "C16, C45, C02"),
    ("Backup infrastructure and backup administration", "Recovery", "Recovery of every service", "Possible shared admin domain with production - primary and recovery can fail together", "No", "C03, C31, C02"),
    ("Integrated EHR vendor", "Supplier / SaaS", "Clinical documentation at all clinics", "Supplier concentration; vendor remote access and updates", "No", "C13, C22"),
    ("Medical-device manufacturers", "Supplier", "Imaging and diagnostic equipment", "Patching controlled by manufacturers; certification limits", "Yes - devices often outside IT oversight", "C09, C27, C43"),
    ("Cloud storage / tenant", "Cloud", "Image transfer, exports, collaboration", "Tenant-wide control plane", "Partly - exports created ad hoc", "C04, C23, C05"),
    ("Clinic networks, Wi-Fi and local storage units", "Network / storage", "Point-of-care access in 10 clinics", "Flat networks assumed; local data outside central controls", "Yes - clinic-level assets", "C06, C17, C27"),
    ("Internet-facing edge (VPN, firewalls, admin interfaces)", "Network", "Remote access for clinicians and vendors", "Single gateway; exposure unknown", "Yes - forgotten interfaces", "C07, C26, C36"),
    ("Telecom carriers", "Supplier", "WAN and internet for all clinics", "Carrier concentration unknown", "No", "C16, C10"),
    ("Interface engine (HL7/DICOM)", "Application", "Lab, pharmacy, imaging data into EHR", "Single integration path", "Yes - legacy protocols", "C32"),
    ("External AI and SaaS services used by staff", "SaaS", "Documentation, correspondence", "Unmanaged; outside contracts", "Yes - shadow IT", "C29, C42"),
    ("Privileged IT administrators (15-person team)", "People", "All infrastructure", "Key-person dependency; standing privileges", "No", "C31, C35"),
]
MATERIALITY = [
    ("Patient safety", "Any credible immediate threat to patient care or clinical decisions exceeds appetite (E5)."),
    ("Health data", "Exposure of health information of many patients, or any exposure of sensitive categories, is material."),
    ("Clinical availability", "Loss of EHR, diagnostics or scheduling at several clinics beyond a working day is material."),
    ("Regulatory", "Reportable confidentiality incident or failure to meet notification duties."),
    ("Financial", "Loss that would require re-prioritizing the IT/cyber budget (analyst threshold: > CAD 250k) - validate with CFO."),
    ("Reputational", "Regional media coverage or loss of referring-partner confidence."),
    ("Recoverability", "Any scenario that can defeat primary and recovery environments together."),
]
GAPS = [
    ("Asset and medical-device inventories; internet-exposed services", "Architecture review, external attack-surface scan"),
    ("Identity design: MFA coverage, privileged and service accounts, help-desk reset procedure", "IAM configuration review, interviews"),
    ("Backup isolation, immutability, restore-test results, RTO/RPO", "Backup architecture review, restore test evidence"),
    ("Cloud tenant configuration, sharing links, logging", "Cloud posture assessment"),
    ("Vendor list, contracts, remote-access and update mechanisms", "Procurement records, supplier assessments"),
    ("Existence of patient portal, in-house code repositories, telehealth platform", "Application inventory, interviews with application owners"),
    ("Incident history since 2020 and how attempts were detected", "Incident records, SOC/EDR logs"),
    ("Staff use of generative AI", "Proxy logs, staff survey"),
    ("IT and cybersecurity budget figures", "Finance"),
]

# ================================================================ SECTION B/C candidate enrichment
EXTRA_STATEMENTS = {
    "C14": "An intrusion is detected, but because the incident response plan has never been tested across clinics, roles, decision rights, forensic engagement and clinical workarounds are improvised, extending containment and amplifying privacy and operational harm.",
    "C15": "An attacker or insider uses the over-privileged ehr-sync-svc service account, whose credentials are stored in scripts and not vaulted, to query and extract large volumes of EHR records at night without triggering review.",
    "C20": "An attacker holding a stolen password floods a clinician with MFA push requests until one is approved, taking over a remote-access session and reaching the EHR.",
    "C34": "A ransomware operator with administrative access encrypts the virtualization hosts in the Montreal data centre, taking down all hosted clinical and administrative servers at once.",
    "C35": "An intruder exploits Active Directory misconfigurations (Kerberoastable service accounts, excessive delegation) to obtain domain-administrator rights, enabling enterprise-wide compromise.",
    "C36": "Clinic workstations running an unsupported operating system are compromised by commodity malware exploiting unpatched flaws, providing footholds on networks that reach the EHR.",
    "C37": "An attacker abuses weak cloud or server controls to run cryptomining workloads, increasing costs and degrading performance of shared resources.",
    "C38": "A malicious script injected into an online payment page captures patients' card details during online payments.",
    "C39": "An intruder enters an unsecured clinic server closet and steals or tampers with the local storage unit or network equipment.",
    "C40": "Because log sources and retention are insufficient, MediBec cannot determine what data an intruder accessed, forcing broad notification and weakening its regulatory position.",
    "C41": "An attacker compromises a clinician's mailbox through phishing and harvests patient information exchanged by e-mail, then uses the mailbox for internal phishing.",
    "C42": "An AI transcription (ambient scribe) SaaS used by clinicians retains or reuses recorded consultations in ways MediBec has not assessed, causing unauthorized disclosure of health information.",
    "C43": "A building IoT device or CCTV camera on the clinic network is compromised and used as an unmanaged foothold to reach clinical systems.",
    "C44": "Because health information is retained beyond need across systems, a breach of any store exposes far more patient records than necessary, increasing notification and harm.",
    "C45": "Failure of the single primary firewall pair at the Montreal hub interrupts connectivity for all clinics until hardware is replaced.",
}
STRATEGY = {  # generation strategy tags: TD top-down, BU bottom-up, TH threat-driven, GL generic localized, DP dependency
    "C01": "TH, BU", "C02": "TD, TH", "C03": "DP, BU", "C04": "BU", "C05": "GL", "C06": "GL", "C07": "BU, TH", "C08": "BU",
    "C09": "TD, DP", "C10": "TH", "C11": "TH, TD", "C12": "TD", "C13": "DP", "C14": "BU", "C15": "BU", "C16": "DP, TD",
    "C17": "BU, DP", "C18": "TH", "C19": "GL", "C20": "BU", "C21": "GL", "C22": "DP, TH", "C23": "TH, DP", "C24": "TH",
    "C25": "GL", "C26": "GL, BU", "C27": "GL", "C28": "GL", "C29": "TD, TH", "C30": "TH", "C31": "TH, DP", "C32": "TD, DP",
    "C33": "BU, TH", "C34": "TH, DP", "C35": "BU", "C36": "BU", "C37": "GL", "C38": "GL", "C39": "GL", "C40": "BU",
    "C41": "TH", "C42": "DP, TD", "C43": "GL", "C44": "TD", "C45": "DP",
}
CIA = {"C01": "C, I", "C02": "C, I, A", "C03": "A, I", "C04": "C", "C05": "C", "C06": "C, I", "C07": "C, I, A", "C08": "C, I, A",
       "C09": "I, A", "C10": "A", "C11": "C", "C12": "I", "C13": "C, I, A", "C14": "C, A", "C15": "C", "C16": "A", "C17": "C, A",
       "C18": "I", "C19": "C", "C20": "C, I", "C21": "C", "C22": "C, I, A", "C23": "C, I, A", "C24": "C", "C25": "C", "C26": "C, I, A",
       "C27": "I, A", "C28": "C", "C29": "C", "C30": "C, I", "C31": "I, A", "C32": "C, I", "C33": "C", "C34": "A", "C35": "C, I, A",
       "C36": "C, I", "C37": "A", "C38": "C", "C39": "C, A", "C40": "C", "C41": "C", "C42": "C", "C43": "I, A", "C44": "C", "C45": "A"}

# ---------------------------------------------------------------- 12-criterion scores (1-5)
CRIT = ["Business criticality", "Asset criticality", "Threat relevance", "Exposure / vulnerability", "Potential impact",
        "Regulatory / legal", "Operational resilience", "Dependency / concentration", "Evidence strength", "Risk velocity",
        "Control uncertainty", "Decision usefulness"]
CRIT_SHORT = ["BC", "AC", "TR", "EX", "IM", "RL", "OR", "DC", "EV", "RV", "CU", "DU"]
SCORES = {
    "C01": "5 5 5 4 4 4 3 4 5 4 4 5", "C02": "5 5 5 4 5 5 5 4 4 5 4 5", "C03": "5 5 4 4 5 3 5 5 4 4 5 5",
    "C04": "4 5 4 4 4 5 2 3 4 4 4 4", "C05": "3 4 3 3 4 4 2 2 2 4 4 3", "C06": "3 3 3 3 3 3 3 2 2 3 4 3",
    "C07": "5 5 5 4 5 4 4 4 3 5 4 5", "C08": "5 5 5 4 4 4 4 3 5 3 5 5", "C09": "5 5 3 4 5 4 4 4 3 4 5 5",
    "C10": "2 3 3 4 2 1 3 3 2 5 3 2", "C11": "4 5 5 4 4 5 1 2 4 2 4 4", "C12": "5 5 2 3 5 5 3 3 2 3 5 4",
    "C13": "5 5 4 4 5 4 4 5 3 4 5 5", "C14": "4 4 3 4 4 3 4 3 4 3 4 4", "C15": "4 5 4 4 4 4 2 3 5 3 4 4",
    "C16": "5 5 3 4 5 3 5 5 3 5 4 5", "C17": "3 4 3 4 3 4 2 2 3 2 4 3", "C18": "2 3 5 3 3 1 1 2 3 4 3 3",
    "C19": "2 3 4 3 2 3 1 1 2 2 3 2", "C20": "5 5 5 4 4 4 3 4 5 4 4 5", "C21": "3 4 3 3 4 4 2 2 1 4 4 3",
    "C22": "4 5 2 4 5 3 4 5 2 5 5 4", "C23": "4 5 4 3 5 4 3 5 2 4 5 4", "C24": "3 4 5 4 2 4 1 1 3 3 3 3",
    "C25": "2 3 2 3 2 3 1 2 1 3 3 2", "C26": "4 5 4 3 5 3 4 4 2 5 5 4", "C27": "3 4 3 3 3 2 3 2 2 3 4 3",
    "C28": "2 3 3 3 3 4 1 1 2 1 3 2", "C29": "3 4 5 4 3 5 1 3 3 3 5 5", "C30": "4 5 4 4 4 3 3 4 2 5 5 4",
    "C31": "4 5 2 4 5 3 5 4 2 5 5 4", "C32": "4 5 2 3 5 4 2 3 1 3 5 3", "C33": "2 2 4 4 2 2 1 2 3 4 3 3",
    "C34": "4 5 4 3 5 3 5 5 2 5 4 4", "C35": "4 5 4 3 4 3 4 5 2 4 4 3", "C36": "3 3 4 4 3 2 3 2 2 3 3 3",
    "C37": "1 2 3 2 1 1 1 1 1 2 2 1", "C38": "1 2 2 1 2 3 1 1 1 3 2 1", "C39": "2 3 2 3 3 2 2 2 1 2 3 2",
    "C40": "3 4 3 4 3 4 2 2 4 2 5 4", "C41": "4 4 5 4 4 4 2 3 4 4 4 3", "C42": "3 4 3 3 3 4 2 3 1 2 4 3",
    "C43": "2 3 3 3 2 2 2 2 1 3 3 2", "C44": "3 4 3 4 3 4 1 1 2 1 3 3", "C45": "4 4 3 3 4 2 5 5 2 5 3 4",
}
SCORES = {k: [int(x) for x in v.split()] for k, v in SCORES.items()}
RATIONALE = {
    "C01": "High: phishing targeting clinic/billing staff observed (E6) and push MFA approved from unusual geography; identity gates every crown jewel. Lower: direct operational impact limited unless escalated.",
    "C02": "High on all dimensions: network-wide clinical disruption, data theft, velocity of hours; full chain visible in exercise timeline (E6). Evidence 4: chain is simulated, not a confirmed incident.",
    "C03": "Backup failures before encryption (E6) and no isolation evidence; defeats recovery of every service. Stage of C02 rather than independent exposure.",
    "C04": "External download of medical_image_export.zip (E6); bulk PHI; high regulatory weight. Limited operational impact.",
    "C05": "Plausible where in-house development exists (E3) but repositories and secret practices unknown - evidence weak.",
    "C06": "Wireless controls listed for audit (E7) with no evidence either way; consequence arises mainly as an entry path to other scenarios.",
    "C07": "Edge-device exploitation is a leading sector vector; patching lag documented (E3, E7); high velocity. Exposure inventory unknown.",
    "C08": "Strong evidence: 2-person team, PowerShell alert closed, uncorrelated signals (E3, E6). A control condition that amplifies other scenarios rather than a distinct threat chain.",
    "C09": "Only direct patient-safety path via equipment; inventory and segmentation unknown (E4); certification constrains patching. Threat frequency lower than IT-focused attacks.",
    "C10": "Fast-moving but clinics continue in person; low regulatory weight; online-service criticality not documented.",
    "C11": "Insider snooping is recurrent in healthcare; EHR access central (E7); high privacy weight. Little operational impact.",
    "C12": "Severe patient-safety and regulatory consequence; integrity controls absent (E8). Threat relevance and evidence low - classic low-frequency/high-consequence.",
    "C13": "Multiple critical vendors (EHR, devices, cloud) with no assurance evidenced (E7); supplier concentration; outside MediBec's direct control.",
    "C14": "IR untested (MED-CYR-15); amplifier rather than distinct scenario; decisions overlap with C08.",
    "C15": "Direct evidence of unusual ehr-sync-svc queries (E6); same control family and owner as C11.",
    "C16": "Single hub serves all clinics (E2); no alternate site evidenced; enterprise-wide availability loss; partly non-malicious.",
    "C17": "Local storage exists (E2) and data sprawl is an open question (E4); moderate consequence per clinic.",
    "C18": "Frequent fraud type; billing staff targeted (E6); consequence financial and bounded; standard process controls.",
    "C19": "Near-certain occurrence but small data volume; standard MDM control; little decision value.",
    "C20": "Directly evidenced (E6); same exposure and treatment as C01.",
    "C21": "High consequence if a patient portal exists, but its existence is only inferred from 'records access' (E8) - evidence very weak.",
    "C22": "Rare but enterprise-wide; supplier concentration; prevention largely outside MediBec's control.",
    "C23": "Control-plane takeover with tenant-wide consequence; token theft bypasses push MFA; cloud logging unknown (E4).",
    "C24": "Very frequent human error; limited individual impact; privacy register obligations.",
    "C25": "Telehealth use not documented; limited consequence.",
    "C26": "High consequence and velocity if interfaces are exposed; exposure unknown.",
    "C27": "Healthcare-specific path into imaging; consequence overlaps device scenario.",
    "C28": "Lifecycle gap; cheap fix; low decision value.",
    "C29": "Near-certain staff use of public AI by 2026; no policy or controls; systemic privacy and regulatory exposure; unique decisions (policy, sanctioned tool).",
    "C30": "Bypasses MFA investments; process weakness unknown; same identity exposure as C01 with different control.",
    "C31": "Extreme availability and recoverability consequence; low frequency; standing privileges and key-person dependency (E3).",
    "C32": "Patient-safety integrity path; cleartext interfaces assumed; very weak evidence; same consequence family as C12.",
    "C33": "Look-alike domain observed (E6); harm mostly to patients outside MediBec systems; reputational.",
    "C34": "Destructive stage of ransomware; consolidates into C02.",
    "C35": "Escalation technique within C02/C01 chains.",
    "C36": "Endpoint weakness; entry path overlapping C07 and C02.",
    "C37": "Low mission impact.",
    "C38": "Card processing not evidenced; out of scope.",
    "C39": "Physical security out of scope.",
    "C40": "Strong inference from E4 ('are logs sufficient?'); amplifier of breach consequences; overlaps C08.",
    "C41": "Common path; overlaps C01 chain.",
    "C42": "AI scribe use not documented; overlaps C29 (AI) and C13 (vendor).",
    "C43": "Generic; overlaps C09 treatment (segmentation).",
    "C44": "Amplifier of privacy scenarios; overlaps C04/C17 treatment.",
    "C45": "Component of hub single point of failure (C16).",
}
ESCALATION_CODES = {
    "S": "Human safety", "ES": "Essential service interruption", "CD": "Catastrophic data loss", "SY": "Systemic organizational failure",
    "PV": "Severe privacy consequences", "RG": "Major regulatory breach", "FN": "Existential financial loss", "PI": "Compromise of highly privileged infrastructure",
    "BK": "Destruction of backup/recovery", "PR": "Simultaneous failure of primary and recovery", "SC": "Critical supply-chain concentration", "MU": "Spread across multiple units/clinics",
}
ESC = {"C01": "PV, PI, MU", "C02": "S, ES, CD, SY, PV, RG, BK, MU", "C03": "CD, BK, PR", "C04": "PV, RG", "C05": "PV", "C07": "PI, MU",
       "C08": "SY, MU", "C09": "S, ES", "C11": "PV, RG", "C12": "S", "C13": "SC, PI, MU", "C14": "SY", "C15": "PV, PI", "C16": "S, ES, SY, MU",
       "C17": "PV", "C20": "PI", "C21": "PV", "C22": "SC, SY, MU", "C23": "PI, PV, MU", "C26": "PI", "C27": "S", "C29": "PV, RG",
       "C30": "PI", "C31": "PI, BK, PR, SY", "C32": "S", "C34": "PI, ES, MU", "C35": "PI, SY", "C40": "RG", "C41": "PV", "C42": "PV",
       "C44": "PV", "C45": "ES, SY"}
CONF = {  # selection confidence
    "C01": "High", "C02": "High", "C03": "Medium", "C04": "Medium", "C05": "Low", "C06": "Low", "C07": "Medium", "C08": "High", "C09": "Medium",
    "C10": "Low", "C11": "Medium", "C12": "Low", "C13": "Medium", "C14": "Medium", "C15": "High", "C16": "Medium", "C17": "Low", "C18": "Medium",
    "C19": "Medium", "C20": "High", "C21": "Low", "C22": "Low", "C23": "Low", "C24": "Medium", "C25": "Low", "C26": "Low", "C27": "Low",
    "C28": "Low", "C29": "Medium", "C30": "Low", "C31": "Low", "C32": "Low", "C33": "Medium", "C34": "Low", "C35": "Low", "C36": "Low",
    "C37": "Medium", "C38": "High", "C39": "High", "C40": "Medium", "C41": "Medium", "C42": "Low", "C43": "Low", "C44": "Low", "C45": "Low",
}
EVIDENCE_TYPE = {  # dominant evidence basis
    "C01": "Verified org evidence (exercise) + sector", "C02": "Verified org evidence (exercise) + sector", "C03": "Verified org evidence (exercise)",
    "C04": "Verified org evidence (exercise)", "C08": "Verified org evidence (case + exercise)", "C15": "Verified org evidence (exercise)",
    "C20": "Verified org evidence (exercise)", "C11": "External/sector + case", "C16": "Case architecture + assumption", "C07": "External/sector + case",
    "C09": "Case + external/sector", "C13": "Case + external/sector", "C29": "External/sector + assumption", "C33": "Verified org evidence (exercise)",
    "C40": "Case (open question) + inference", "C14": "Case (scenario library)", "C18": "External/sector + exercise",
}
DISP = {  # Select / Consolidate / Consider / Defer -> target
    "C01": ("Select", "P01"), "C20": ("Consolidate", "P01"), "C23": ("Consolidate", "P01"), "C30": ("Consolidate", "P01"), "C41": ("Consolidate", "P01"),
    "C02": ("Select", "P02"), "C03": ("Consolidate", "P02"), "C08": ("Consolidate", "P02"), "C14": ("Consolidate", "P02"), "C34": ("Consolidate", "P02"), "C35": ("Consolidate", "P02"), "C40": ("Consolidate", "P02"),
    "C07": ("Select", "P03"), "C26": ("Consolidate", "P03"), "C36": ("Consolidate", "P03"),
    "C09": ("Select", "P04"), "C06": ("Consolidate", "P04"), "C27": ("Consolidate", "P04"), "C43": ("Consolidate", "P04"),
    "C12": ("Select", "P05"), "C32": ("Consolidate", "P05"),
    "C11": ("Select", "P06"), "C15": ("Consolidate", "P06"),
    "C04": ("Select", "P07"), "C05": ("Consolidate", "P07"), "C17": ("Consolidate", "P07"), "C44": ("Consolidate", "P07"),
    "C13": ("Select", "P08"), "C22": ("Consolidate", "P08"),
    "C16": ("Select", "P09"), "C45": ("Consolidate", "P09"),
    "C29": ("Select", "P10"), "C24": ("Consolidate", "P10"), "C42": ("Consolidate", "P10"),
    "C31": ("Consider", "Watch list - explicit management review (escalation flags)"),
    "C21": ("Consider", "Promote if a patient portal is confirmed"),
    "C18": ("Defer", "Watch list - standard finance controls"), "C33": ("Defer", "Watch list - communications controls"),
    "C10": ("Defer", "Watch list"), "C19": ("Defer", "Standard control (MDM)"), "C25": ("Defer", "Evidence gap - telehealth use"),
    "C28": ("Defer", "Standard control (disposal)"), "C37": ("Defer", "Low materiality"), "C38": ("Defer", "Out of scope"), "C39": ("Defer", "Out of scope (physical)"),
}
assert set(DISP) == {c[0] for c in M.CANDIDATES} == set(SCORES), set(SCORES) ^ set(DISP)

def cand_rows():
    rows = []
    for c in M.CANDIDATES:
        cid = c[0]
        m = re.search(r"\((S\d+)", c[7])
        sid = m.group(1) if m else None
        stmt = SC[sid]["statement"] if sid else EXTRA_STATEMENTS[cid]
        rows.append(dict(id=cid, name=c[1], statement=stmt, asset=c[4], threat=c[2], vuln=c[3], consequence=c[5], ref=c[6],
                         prev=sid or "-", strategy=STRATEGY[cid], cia=CIA[cid]))
    return rows

# ================================================================ SECTION D
FINAL = [
    dict(id="P01", name="Identity takeover of clinical, privileged or cloud-administrator accounts",
         statement="A cybercriminal obtains valid credentials or session tokens for clinic administrators, clinicians or cloud administrators - through EHR-themed phishing, MFA push fatigue, help-desk reset fraud or token theft - and exploits push-only MFA, absent conditional access and weak reset verification to access the EHR, mail and the cloud tenant, leading to health-data exposure and a foothold for destructive attacks.",
         objective="O2 health information; O1 clinical continuity (as precursor)", assets="Identity/MFA, cloud tenant, EHR, mail",
         threat="Cybercriminal / initial-access broker", vulns="Push MFA without number matching or phishing resistance; no conditional access or token binding; help-desk reset verification unknown; users can consent to apps",
         consequences="Unauthorized access to patient records and mail; reportable confidentiality incident; persistence for ransomware (P02)", deps="Directory and cloud IdP (concentration)", controls="Push MFA on remote access (E6); e-mail filtering (E2)",
         appetite="Health-data exposure of many patients exceeds low appetite; precursor to safety-relevant outages", cands=["C01", "C20", "C23", "C30", "C41"], prev=["S1", "S20", "S27"],
         rationale="Most evidenced and most frequent entry path; one identity plane gates every crown jewel. Four variants (phishing, MFA fatigue, help-desk reset, token theft) consolidated so the portfolio is not dominated by identity attacks; they share owner (CIO) and treatment family (phishing-resistant MFA, conditional access, reset verification).",
         evidence="Verified org evidence (exercise injects E6: phishing, MFA approval); external/sector; assumption (reset procedure, tenant settings)", conf="High",
         validate="MFA method and coverage; conditional-access policies; help-desk reset procedure; cloud app-consent setting; sign-in logs for E6 indicators",
         fair=("High", "Medium", "Low", "High")),
    dict(id="P02", name="Ransomware with data theft and backup destruction halting multi-clinic operations",
         statement="A ransomware affiliate enters through P01 or P03, is not detected because alerts are mis-triaged and logs are incomplete, escalates to domain administrator through Active Directory weaknesses, deletes backups reachable from the production domain, exfiltrates health data and encrypts servers, hypervisors and clinic storage, halting EHR, scheduling and diagnostics across clinics while recovery fails.",
         objective="O1 clinical continuity; O2; O3; O4", assets="EHR, hypervisors, file shares, scheduling, backup servers, clinic storage",
         threat="Ransomware-as-a-service affiliate (double extortion)", vulns="Weak alert triage and no 24x7 monitoring; flat network; backups in production admin domain; untested restore and IR",
         consequences="Multi-day multi-clinic outage; delayed care; data theft and notification; possible permanent loss if recovery fails; media attention", deps="Montreal DC, backup infrastructure, AD, EDR/MDR",
         controls="Firewalls, IDS/IPS, antimalware, EDR (E2, E6); on/off-site backups (E2 - isolation unknown); defined incident roles (E6 - untested)",
         appetite="Credible immediate threat to patient care - no residual acceptable without Board decision", cands=["C02", "C03", "C08", "C14", "C34", "C35", "C40"], prev=["S2", "S3", "S8"],
         rationale="Highest combined consequence; full chain visible in exercise; hits several escalation criteria (safety, essential service, backup destruction, primary+recovery failure). Detection gaps, untested IR and backup compromise are stages of this chain, so they are analysed inside it rather than as separate scenarios.",
         evidence="Verified org evidence (exercise timeline E6); case (E2, E7); external/sector", conf="High",
         validate="EDR coverage and triage records; log sources and retention; AD security assessment; backup isolation and last restore test; IR plan test history",
         fair=("High", "High", "Low", "Very high")),
    dict(id="P03", name="Exploitation of exposed internet-facing systems (unpatched edge devices, admin interfaces, end-of-life systems)",
         statement="A cybercriminal or state-linked actor exploits a known vulnerability in an unpatched VPN or firewall appliance, or default/stuffed credentials on an internet-exposed management interface, because MediBec lacks an attack-surface inventory and timely patching, gaining administrative access to infrastructure and a path to data theft or P02.",
         objective="O1; O2", assets="Remote-access gateway, firewalls, hypervisor/storage management interfaces, end-of-life systems",
         threat="Cybercriminal / state-linked actor (mass exploitation)", vulns="Patch delays (E3, E7); unknown internet exposure (E4); admin interfaces without MFA (assumption)",
         consequences="Infrastructure compromise; outage; data access", deps="Edge gateway (single remote-access path)", controls="Firewalls, IDS/IPS (E2)",
         appetite="Critical vulnerabilities on internet-facing systems must be fixed within a short timeframe (E5)", cands=["C07", "C26", "C36"], prev=["S6", "S23"],
         rationale="Technical entry path distinct from identity (P01): different controls (attack-surface management, patch SLAs), owner (Infrastructure) and velocity (days from disclosure to exploitation). Directly tied to an explicit appetite rule on critical vulnerabilities.",
         evidence="Case (E3, E7); external/sector; unknown (actual exposure)", conf="Medium",
         validate="External attack-surface scan; patch status of edge devices; list of internet-exposed admin interfaces; EOL inventory",
         fair=("High", "High", "Low", "High")),
    dict(id="P04", name="Compromise of connected medical devices disrupting diagnostics and threatening patient safety",
         statement="An attacker or spreading malware reaches a clinic network - via infected workstation, clinic Wi-Fi, patient-supplied imaging media or building IoT - and exploits unpatched or default-credential medical devices sharing that network, disrupting imaging and diagnostic equipment, altering device data and using devices as persistent footholds.",
         objective="O1 safe care", assets="Imaging modalities and consoles, diagnostic devices, clinic LAN",
         threat="Cybercriminal / commodity malware", vulns="Incomplete device inventory (E4); patching restricted by certification (E3); no segmentation evidence; media import without scanning (assumption)",
         consequences="Postponed procedures; incorrect or unavailable diagnostics; patient-safety review", deps="Device manufacturers; clinic networks (peripheral assets)",
         controls="Hub firewalls and IDS/IPS (E2 - east-west coverage unknown)", appetite="Patient-safety clause - no credible immediate threat to care may be accepted (E5)",
         cands=["C09", "C06", "C27", "C43"], prev=["S7", "S24", "S12"],
         rationale="Only scenario where the cyber event directly affects medical equipment; peripheral assets outside IT oversight (instruction s.2-3); certification limits make treatment a distinct management decision. Wi-Fi, media and IoT are entry paths into the same exposure.",
         evidence="Case (E2, E4); external/sector; assumption (segmentation, media handling)", conf="Medium",
         validate="Networked device inventory with OS/patch level; MDS2 forms; network segmentation diagrams; Wi-Fi and guest isolation; media import procedure",
         fair=("Medium", "Medium", "Low", "Very high")),
    dict(id="P05", name="Manipulation of clinical data (records or interface messages) leading to unsafe care",
         statement="An attacker using a compromised clinical account, a malicious insider, or an attacker positioned on the network alters medication, allergy, laboratory or imaging data - in the EHR or in cleartext HL7/DICOM interface traffic - without detection because integrity monitoring and reconciliation are absent, leading to incorrect clinical decisions.",
         objective="O1 safe care; O4 trust", assets="EHR records, lab/pharmacy results, interface engine",
         threat="Extortion-motivated attacker, saboteur or malicious insider", vulns="No integrity monitoring or reconciliation (E8); cleartext interfaces (assumption); broad write privileges (assumption)",
         consequences="Wrong medication or diagnosis; clinical safety review; loss of trust in the record", deps="Interface engine; EHR vendor",
         controls="EHR audit logging (E6)", appetite="Patient-safety clause (E5); low-frequency/high-consequence - must not be excluded for low probability",
         cands=["C12", "C32"], prev=["S10", "S29"],
         rationale="Low-frequency/high-consequence integrity risk; the portfolio would otherwise treat integrity only as a side effect. Distinct controls (integrity monitoring, reconciliation, interface encryption) and owner (CMO/Clinical Ops).",
         evidence="Case (E8 control expectation); assumption; very limited sector frequency data", conf="Low",
         validate="EHR audit-trail capability; interface protocols (TLS or cleartext); reconciliation practices; write-privilege model",
         fair=("Low", "Medium", "Low", "Very high")),
    dict(id="P06", name="Misuse of legitimate EHR or service-account access to extract patient records",
         statement="A malicious or curious employee, or an attacker who has taken over the over-privileged ehr-sync-svc service account, uses legitimate but excessive access to query and export patient or billing records, because access is broad, service accounts are not vaulted and EHR access is not monitored, resulting in a privacy breach.",
         objective="O2 privacy", assets="EHR data, billing data, service accounts",
         threat="Malicious/curious insider; attacker using a service account", vulns="Broad roles (assumption); un-vaulted service account (E6); no access analytics or recertification (E7); no DLP",
         consequences="Privacy breach, disciplinary and legal action, notification", deps="EHR role model; integration accounts", controls="EHR audit log exists (E6); encrypted storage (E2)",
         appetite="High-risk data stores must have access control, logging and monitoring (E5)", cands=["C11", "C15"], prev=["S5"],
         rationale="Insider misuse is a recurrent healthcare exposure and is directly evidenced by the service-account anomaly. Distinct from P01 (legitimate access, no perimeter crossing) and P10 (malicious intent); owner is the Privacy officer.",
         evidence="Verified org evidence (exercise: ehr-sync-svc); external/sector; assumption (role model)", conf="Medium",
         validate="EHR role matrix; service-account inventory and privileges; audit-log review practice; last access recertification",
         fair=("Medium", "Low", "Low", "High")),
    dict(id="P07", name="Bulk exposure of health data held outside core systems (cloud exports, APIs, clinic storage)",
         statement="An opportunistic actor or intruder obtains bulk patient data from stores that sit outside the EHR's controls - cloud storage used for image transfer shared through long-lived links, API keys leaked from code or configuration, and unmanaged local clinic storage - because posture management, secret management and data minimization are absent, causing a large reportable breach.",
         objective="O2 privacy; O4 trust", assets="Cloud storage, API integrations, local clinic storage, exports",
         threat="Opportunistic scanner / cybercriminal", vulns="Permissive sharing and weak cloud logging (E4, E6); no secret management (E7); data sprawl (E4); excessive retention",
         consequences="Large-scale health-data exposure; notification; reputational harm", deps="Cloud provider; integration partners",
         controls="Encrypted storage (E2 - does not prevent valid-link or key access)", appetite="High-risk data stores must have encryption, access control, logging and monitoring (E5)",
         cands=["C04", "C05", "C17", "C44"], prev=["S4", "S11", "S17"],
         rationale="Data-at-rest exposure outside the EHR is evidenced (external download of image export) and produces the largest breach volumes. Consolidates three variants that share the treatment decision (data discovery, posture management, minimization) and owner.",
         evidence="Verified org evidence (exercise: cloud download); case (E2, E4); assumption (repositories)", conf="Medium",
         validate="Cloud sharing configuration and object logs; inventory of exports; secret-scanning of repositories; content of clinic storage units",
         fair=("High", "Low", "Low", "High")),
    dict(id="P08", name="Compromise through a critical supplier (vendor remote access or trojanized software update)",
         statement="A threat actor compromises an EHR, diagnostic, device or IT-support supplier and enters MediBec through the supplier's standing remote access or a malicious signed software update, bypassing perimeter controls, because supplier assurance, contract clauses, access brokering and update staging are absent.",
         objective="O1; O2", assets="Vendor-managed systems, EHR components, endpoints running supplier agents",
         threat="Supply-chain attacker (criminal or state-linked)", vulns="Standing vendor access (assumption); no vendor tiering or assessments (E7); automatic updates without staging (assumption)",
         consequences="Trusted-path intrusion across many systems; outage; breach; contractual disputes", deps="EHR vendor and critical suppliers (concentration)",
         controls="Firewalls (E2); vendor coordination role in IR (E6)", appetite="Critical vendors must meet security expectations and support incident notification (E5)",
         cands=["C13", "C22"], prev=["S9", "S19"],
         rationale="Critical supply-chain concentration is a mandatory escalation criterion; residual stays above tolerance even with funding, so it drives transfer and acceptance decisions rather than spending. Remote-access and update vectors share owner (Procurement/CIO) and the supplier-assurance decision.",
         evidence="Case (E2, E5, E7); external/sector; assumption (access design)", conf="Medium",
         validate="Critical supplier list; remote-access methods; contract clauses (notification, audit); update mechanisms of critical software",
         fair=("Medium", "High", "Low", "Very high")),
    dict(id="P09", name="Loss of the Montreal hub or WAN isolating all clinics from clinical systems",
         statement="A carrier failure, attack on edge network devices, failure of the single primary firewall pair or data-centre incident takes the Montreal hub offline; because all clinics depend on it without tested redundancy, alternate site or rehearsed downtime procedures, EHR, imaging and pharmacy access is lost network-wide.",
         objective="O1 clinical continuity", assets="Montreal DC, WAN, firewalls, carrier links",
         threat="Technical failure, carrier outage or attacker targeting network infrastructure", vulns="Single hub and possibly single carrier (assumption); firewall redundancy unknown; no alternate site evidenced; downtime procedures untested (E7)",
         consequences="Network-wide loss of clinical systems for hours to days; safety risk from missing history", deps="Hub, carriers, firewalls (single point of failure)",
         controls="High-speed fibre links (E2); off-site backups (E2)", appetite="Clinical services must have tested recovery and workaround procedures (E5)",
         cands=["C16", "C45"], prev=["S16"],
         rationale="Instruction s.3 requires explicit analysis of single points of failure; this is the organization's largest concentration risk and is independent of any attacker, so it is not captured by P02. Distinct decision (redundancy / alternate site investment, IT-funded).",
         evidence="Case architecture (E2); assumption (redundancy)", conf="Medium",
         validate="Network architecture; carrier diversity; firewall HA; DR site; clinic downtime procedures and last test",
         fair=("Medium", "n/a (includes non-malicious)", "Low", "Very high")),
    dict(id="P10", name="Uncontrolled disclosure of patient information by staff through unapproved AI tools and communications",
         statement="Clinicians and administrative staff paste identifiable patient information into public generative-AI or unassessed AI-scribe services, or misdirect e-mails and faxes, because MediBec has no AI acceptable-use policy, sanctioned tool, web/DLP controls or secure referral channel, resulting in systemic uncontrolled disclosure of health information and possible cross-border transfer.",
         objective="O2 privacy; O5 governed innovation", assets="Clinical notes, correspondence, referrals",
         threat="Negligent insider; external AI/SaaS provider handling", vulns="No AI policy or approved tool; no web category or DLP controls; manual referral channels (assumption)",
         consequences="Systemic privacy non-compliance; notification; clinical errors from unchecked AI output", deps="External AI and SaaS providers (unmanaged)",
         controls="Privacy and compliance function exists (s.4)", appetite="Low appetite for health-data confidentiality; moderate appetite for governed innovation (E5)",
         cands=["C29", "C24", "C42"], prev=["S26", "S21"],
         rationale="Chosen over the higher-scoring C31 (admin sabotage) for portfolio coverage and decision usefulness: it is the only material negligent-insider and emerging-technology exposure, is near-certain to occur, and drives decisions (AI policy, sanctioned tool, controls) that no other scenario triggers. C31's treatments are largely delivered by P01/P02 controls.",
         evidence="External/sector (AI adoption); assumption (MediBec usage); case (appetite for governed innovation)", conf="Medium",
         validate="Proxy/DNS logs for AI services; staff survey; referral channels in use; any AI scribe pilots",
         fair=("Very high", "Low", "Low", "Medium")),
]

WHY = {  # 6 questions per final scenario
    "P01": ["Identity gates every crown jewel and remote/cloud access is central to MediBec's model.", "Phishing lure and approved MFA push from unusual geography (E6).", "Health-data confidentiality (O2); precursor to O1 disruption.", "Push-only MFA, no conditional access, unknown reset verification.", "Unauthorized EHR/mail access; reportable breach; ransomware foothold.", "Highest likelihood entry path with strongest evidence; variants consolidated."],
    "P02": ["Clinics depend on central services; healthcare is a sustained ransomware target.", "Full exercise timeline; backup failures; alert closed as low (E6).", "Safe continuous care (O1) and all others.", "Weak triage, flat network, backups reachable, untested IR.", "Multi-clinic outage, data theft, failed recovery.", "Largest combined consequence; several mandatory escalation criteria."],
    "P03": ["Remote access is essential and edge devices are prime targets.", "Documented patching constraints (E3, E7); exposure unknown (E4).", "O1 and O2 via infrastructure compromise.", "Patch lag, unknown exposed interfaces, possible default credentials.", "Infrastructure takeover, outage, data access.", "Distinct control set and owner; tied to explicit appetite rule on critical vulnerabilities."],
    "P04": ["Medical equipment is interconnected with the EHR environment (E2).", "Inventory and segmentation are open questions (E4); certification constraints (E3).", "Safe care (O1).", "Unpatchable devices on shared networks; peripheral entry paths.", "Unavailable or incorrect diagnostics; patient-safety risk.", "Only direct safety path through equipment; peripheral assets."],
    "P05": ["Clinical decisions rely on EHR, lab and pharmacy data (E1).", "Integrity controls listed as expected but absent (E8).", "Safe care (O1) and trust (O4).", "No integrity monitoring; cleartext interfaces; broad write access.", "Wrong treatment; loss of confidence in the record.", "Low-frequency/high-consequence; only integrity-centred scenario."],
    "P06": ["EHR access is central and broad; insiders are frequent actors in healthcare.", "ehr-sync-svc anomaly (E6); access reviews not evidenced (E7).", "Privacy (O2).", "Broad roles; un-vaulted service account; no monitoring.", "Privacy breach, legal and HR consequences.", "Distinct actor and controls from P01/P10; direct evidence."],
    "P07": ["Image sharing and exports use cloud storage; data spread across clinics.", "External download of image export (E6); sprawl question (E4).", "Privacy (O2), trust (O4).", "Permissive sharing, no posture or secret management, data sprawl.", "Large-scale reportable breach.", "Largest breach volumes; evidenced; consolidates variants."],
    "P08": ["MediBec relies on EHR, device, cloud and support vendors.", "Vendor controls listed only as expectations (E5, E7).", "O1 and O2 through trusted paths.", "Standing vendor access; no assurance; unstaged updates.", "Trusted-path intrusion across many systems.", "Mandatory supply-chain concentration criterion; drives transfer decisions."],
    "P09": ["All clinics connect through one Montreal hub (E2).", "Architecture documented; redundancy not evidenced.", "Clinical continuity (O1).", "Single hub, possible single carrier/firewall pair, no alternate site.", "Network-wide loss of clinical systems.", "Largest single point of failure; independent of attackers so not covered by P02."],
    "P10": ["Clinicians are adopting AI; MediBec pursues governed innovation (E5).", "Sector evidence; no MediBec policy documented.", "Privacy (O2), governed innovation (O5).", "No AI policy, sanctioned tool or controls.", "Systemic uncontrolled disclosure; clinical errors.", "Only negligent-insider/emerging-tech exposure; unique decisions."],
}
WHY_Q = ["1. Why relevant to MediBec?", "2. Organizational evidence", "3. Asset / objective threatened", "4. Weakness or condition", "5. Material consequence", "6. Why selected over others?"]

STAKE = ["Executive mgmt", "Cybersecurity", "IT operations", "ERM / risk", "Clinical Ops / CMO", "Privacy", "Legal", "Compliance", "Finance", "Internal audit", "Procurement / vendor mgmt", "BCP", "Biomedical engineering", "Clinic managers"]
VALID = {  # R = must validate, C = consult
    "P01": "C R R C C R - - - C - - - C", "P02": "R R R R R R R C C C C R C R", "P03": "C R R C - - - C - C C - - -",
    "P04": "C R R C R - - C - C C C R R", "P05": "C R C C R R R C - C - - C C", "P06": "C R C C C R R R - C - - - C",
    "P07": "C R R C C R R R - C C - - C", "P08": "R R R R C C R C R C R C C -", "P09": "R C R R R - - - R C C R - R",
    "P10": "R R C C R R R R - C C - - C",
}
DISAGREE = {
    "P01": "Clinicians may resist stronger MFA and conditional access at point of care; IT vs Clinical Ops on login friction.",
    "P02": "Containment speed (Cybersecurity) vs care continuity (Clinical Ops); ransom stance (Executive vs Legal/Finance).",
    "P03": "Patch windows: IT operations and clinics prefer fewer outages than security SLAs imply.",
    "P04": "Biomedical engineering and manufacturers may dispute feasibility of patching/segmentation; Clinical Ops on device downtime.",
    "P05": "Likelihood contested - Clinical Ops may rate it very low; Cybersecurity emphasizes consequence.",
    "P06": "Privacy vs clinical staff on monitoring of access; HR/legal on employee monitoring limits.",
    "P07": "Radiology needs easy external sharing; Privacy wants restrictions.",
    "P08": "Procurement and vendors resist new contract clauses; Finance on cost of assurance.",
    "P09": "Whether this is a cyber scenario at all (IT/BCP view) and who funds redundancy (IT vs cyber budget).",
    "P10": "Clinicians see AI as productivity gain; Privacy/Legal see uncontrolled transfer - calibrate between ban and sanctioned tool.",
}
CATEGORIES = ["Confidentiality", "Integrity", "Availability", "Identity & privileged access", "Ransomware / destructive", "Cloud & SaaS",
              "Third-party / supply chain", "Insider", "Application / API", "Infrastructure / network", "Endpoint", "OT / IoT / medical devices",
              "Data protection / privacy", "Fraud / BEC", "Resilience / DR", "Emerging technology (AI)", "Patient safety"]
COVER = {
    "P01": ["Confidentiality", "Integrity", "Identity & privileged access", "Cloud & SaaS", "Endpoint", "Data protection / privacy"],
    "P02": ["Confidentiality", "Integrity", "Availability", "Identity & privileged access", "Ransomware / destructive", "Infrastructure / network", "Endpoint", "Data protection / privacy", "Resilience / DR", "Patient safety"],
    "P03": ["Confidentiality", "Availability", "Identity & privileged access", "Infrastructure / network", "Application / API"],
    "P04": ["Integrity", "Availability", "OT / IoT / medical devices", "Infrastructure / network", "Endpoint", "Patient safety"],
    "P05": ["Integrity", "Application / API", "Insider", "Patient safety"],
    "P06": ["Confidentiality", "Insider", "Identity & privileged access", "Data protection / privacy"],
    "P07": ["Confidentiality", "Cloud & SaaS", "Application / API", "Data protection / privacy"],
    "P08": ["Confidentiality", "Integrity", "Availability", "Third-party / supply chain", "Identity & privileged access"],
    "P09": ["Availability", "Infrastructure / network", "Resilience / DR", "Third-party / supply chain", "Patient safety"],
    "P10": ["Confidentiality", "Insider", "Cloud & SaaS", "Data protection / privacy", "Emerging technology (AI)"],
}
QUALITY = [
    ("Adequately represents material cybersecurity exposure?", "Yes", "All five objectives and the eight crown-jewel groups are threatened by at least one selected scenario; the largest consequences (P02, P09, P04, P05) and most evidenced paths (P01, P06, P07) are included."),
    ("Contains unnecessary duplication?", "No (after consolidation)", "Identity variants (4), ransomware stages (6), data-store variants (3) and supplier vectors (2) were consolidated. Residual overlap: P01 is a precursor to P02 - kept separate because P01 has its own confidentiality consequence and owner."),
    ("Overlooks major dependencies?", "Partly", "Identity, hub, backup, EHR vendor, device manufacturers, cloud and external AI are covered. Not explicitly covered: DNS and telecom carriers beyond the hub (P09 partly), payment/banking providers (C18 deferred)."),
    ("Addresses low-frequency/high-impact risks?", "Yes", "P05 (integrity), P08 (supply chain), P09 (hub) and P04 (devices) retained despite low probability. Admin sabotage (C31) kept on the watch list for explicit review."),
    ("Represents C, I and A exposures?", "Yes", "Confidentiality 7, integrity 5, availability 5 scenarios (Coverage sheet)."),
    ("Includes material third-party and systemic risks?", "Yes", "P08 (suppliers), P09 (hub concentration), P02 (enterprise-wide), P01 (single identity plane)."),
    ("Reflects regulatory and safety considerations?", "Yes", "Patient safety: P02, P04, P05, P09. Privacy/regulatory: P01, P02, P06, P07, P10."),
    ("Supports meaningful management decisions?", "Yes", "Each scenario maps to a distinct decision: MFA/identity (P01), MDR/backup isolation (P02), attack-surface/patch SLAs (P03), device programme (P04), integrity controls (P05), access governance (P06), data posture (P07), supplier assurance/transfer (P08), redundancy investment (P09), AI policy (P10)."),
]
BLIND = [
    ("Fraud / BEC (C18)", "Not in portfolio", "Consequence bounded and treated by low-cost finance controls; confirm payment-verification procedure with Finance. Promote if procedure is absent and payment volumes are large."),
    ("Privileged-insider sabotage (C31)", "Watch list - explicit review", "Scores higher than P10 on raw criteria and triggers escalation flags (privileged infrastructure, backup destruction). Excluded because PAM, immutable backup and offboarding controls in P01/P02 treat it; management should confirm this reliance."),
    ("Patient-facing application flaws (C21)", "Watch list", "Existence of a patient portal is unconfirmed; promote immediately if confirmed."),
    ("Patient-targeted impersonation (C33)", "Deferred", "Look-alike domain observed; harm largely outside MediBec systems; handle through communications and domain monitoring."),
    ("DDoS on online services (C10)", "Deferred", "Online-service criticality undocumented; revisit if online booking becomes essential."),
    ("Physical security (C39)", "Out of scope", "Not assessed; coordinate with physical security owner."),
]
EVIDENCE_PLAN = [
    ("Identity and cloud configuration review (MFA, conditional access, app consent, help-desk reset)", "P01, P06", "Cybersecurity lead", "30 days"),
    ("Compromise assessment of the exercise indicators if any reflect real activity", "P01, P02, P06, P07", "Cybersecurity lead + IR retainer", "Immediate"),
    ("Backup architecture and restore test; AD security assessment; EDR/log coverage review", "P02", "CIO", "60 days"),
    ("External attack-surface scan and patch-status report", "P03", "CIO (Infrastructure)", "30 days"),
    ("Networked medical-device inventory, MDS2 collection, segmentation review", "P04", "Biomedical engineering", "90 days"),
    ("EHR audit-trail and interface-protocol review; reconciliation practices", "P05", "Clinical Ops + integration team", "90 days"),
    ("EHR role matrix and service-account review; access-log sampling", "P06", "Privacy officer", "60 days"),
    ("Cloud storage and sharing review; repository secret scan; clinic storage content survey", "P07", "CIO + Privacy", "60 days"),
    ("Critical supplier register, contracts and remote-access/update mechanisms", "P08", "Procurement", "90 days"),
    ("Network resilience and DR review; carrier diversity; downtime-procedure test", "P09", "CIO + BCP", "90 days"),
    ("AI usage discovery (proxy logs, staff survey)", "P10", "Privacy officer", "30 days"),
    ("Cross-functional validation workshop of this portfolio", "All", "Executive sponsor", "45 days"),
]
WEIGHTS = {  # sensitivity schemes
    "Equal": [1] * 12,
    "Impact-led": [2, 1, 1, 1, 2, 1.5, 1.5, 1, 1, 1, 1, 1],
    "Evidence-led": [1, 1, 1.5, 1.5, 1, 1, 1, 1, 2, 1, 1, 1],
    "Decision-led": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.5, 2],
}
