/* guidelines.js — the guidelines of a complete assessment, as data (1.5.6).

   Until 1.5.5 this list lived inside the Process panel. Three other places read it — the help
   chatbot, the printable checklist and, since 1.5.6, the Step by step window, which is a page of its
   own and must not import a panel that expects the application's DOM and state. So the list moved
   here, where it is nothing but data: no imports, no DOM, safe for any page to read.

   Each guideline carries where it happens, the steps with the exact labels of the screens (checked
   by tools/label_check.py at build time), when it is done, and the routes to the screens.
   © 2026 Marc-André Léger. CC BY-NC 4.0 */
'use strict';

/* 1.5.4 — each guideline in detail: where it happens, the steps with the exact labels of the screens
   (checked by tools/label_check.py at build time), when it is done, and buttons to the screens.
   The user guide, the help chatbot and the printable checklist read this same list. */
export const GUIDELINES = [
  { h: 'Start from the documents', t: 'Create the workspace with all the case documents and let “Extract from documents” propose the profile and the crown jewels. Accept, edit or reject each value, then Save.',
    where: 'Organization → Workspaces → New workspace', routes: [['org/workspaces', 'Workspaces'], ['org/profile', 'Profile & appetite'], ['org/crown', 'Crown jewels']],
    steps: ['Type the workspace name; choose “Real organization” or “Classroom business case”; for teaching tick “Educational case used for training purposes”.',
      'Drop all the case documents (Word, PDF, Excel, PowerPoint, text) on the document zone.',
      'Tick “Extract the profile & appetite from these documents after creation”, “Then extract the crown jewels” and, to go further, “Then import more from the documents”; click “Create workspace”.',
      'Choose “Use AI (preview before sending)” — you see the exact text before anything is sent — or “Rules only (no AI, offline)”.',
      'In the review, edit any value, tick those to keep and click “Put ticked values in the form”; check the fields and click “Save”.',
      'Review the crown jewels and click “Add ticked crown jewels”.',
      'Under “Import from the documents”, tick the targets (information assets, BIA, third parties, existing controls, compliance, incidents, weaknesses, candidate scenarios, parameter evidence, risks, budget, KRIs, people and roles, classroom), click “Start the import”, and for each target tick and click “Add ticked”.',
      'Redo any extraction later with “Extract from documents…” on Profile & appetite or Crown jewels; the AI route of each extraction is set in Settings → AI — local & remote.'],
    done: 'Process steps 1 and 2 show Done: a name and at least one document; at least 8 of the 12 context fields, an appetite rationale and the IT budget.' },
  { h: 'Resolve the UNKNOWN values first', t: 'Extracted values are tagged FACT, INFERENCE, ASSUMPTION, EXTERNAL or UNKNOWN. UNKNOWN items are the information still to collect; ASSUMPTION and EXTERNAL values need validation by the organization.',
    where: 'Organization → Profile & appetite (and Evidence for imported records)', routes: [['org/profile', 'Profile & appetite'], ['org/evidence', 'Evidence']],
    steps: ['Read the coloured tag beside each field label.', 'UNKNOWN: collect the information, enter it and click “Save”.',
      'ASSUMPTION and EXTERNAL: have them validated by the organization; hover the tag to see the source (document or web page). An asterisk after the tag means the value was edited after extraction.',
      'When management has not approved an appetite, use the “Appetite estimator” at the bottom of the tab; its result is labelled an analytical estimate.'],
    done: 'No UNKNOWN tag left on the fields the assessment relies on.' },
  { h: 'Generate 20, keep 10', t: 'In Batch scenarios generate about 20 candidates (rules or AI), review them in the grid, and keep the 10 most material in the register. Ten is where to start; the number rises with the organization\u2019s maturity.',
    where: 'Batch scenarios', routes: [['batch', 'Batch scenarios'], ['register', 'Scenario register'], ['maturity', 'Maturity & resilience']],
    steps: ['Rules: on “Threat patterns × assets” tick the patterns, then “Tick crown jewels + 5 most critical”, choose the threat sources, set “Number of candidates” to 20 and click “Generate candidates”. Keep “Vary the patterns and assets” ticked so the candidates spread across the grid instead of repeating one threat; “Reshuffle” draws a different set and the seed reproduces it.',
      'AI: on “Propose with AI” set the number, add a direction if useful, keep “Include the text of the context documents” ticked and click “Propose candidates” (preview first).',
      'Also available: “From MITRE ATT&CK”, “From CVE”, “From CWE”, and the candidate scenarios imported from the documents (marked [Docs]).',
      'In the grid, edit names, statements and parameters, tick the 10 most material and click “Add … selected to the register”. Ten is the recommended starting number, not a ceiling: carry more as the organization\u2019s cybersecurity maturity grows and it can keep more scenarios current — Maturity & resilience suggests a number from the level you measured, and says why.',
      'In the Scenario register, the checkboxes include or exclude scenarios from the totals.'],
    done: 'Process step 5 shows Done: at least 10 scenarios in the register.' },
  { h: 'Write causal chains, not threat names', t: 'Threat source → weakness → asset → event → consequence. “Ransomware” alone is not a scenario. AI can draft the chain; you accept it field by field.',
    where: 'Scenario editor → Causal chain', routes: [['scenario', 'Scenario editor'], ['vulns/links', 'Suggest links']],
    steps: ['Write the statement in one or two sentences: threat source → weakness → asset → event → consequence.',
      'Or let AI draft it: in the Causal chain card click “Draft it with AI…”, read the preview of exactly what would be sent, and send it. One scenario at a time — a chain is an argument about this organization, not a batch job.',
      'In the review, every proposed field is shown beside what the scenario holds now. Fields that are empty are ticked for you; a field that would replace existing text is left unticked and says so. Edit any draft in place, then click “Apply the ticked fields” — nothing is written until you do, and what you accept is recorded in the revision log.',
      'Fill or check the threat source, initiating event, vulnerabilities or predisposing conditions, assets, processes, existing controls, sequence and consequences.',
      'Link ATT&CK techniques, CWE and CVE; “Suggest vulnerabilities for this scenario…” opens Vulnerabilities → Suggest links for that scenario.'],
    done: 'Every scenario in the register reads as a complete causal chain.' },
  { h: 'Record what already protects you, then measure the resilience it adds up to', t: 'An assessment with no record of existing controls has to guess at θ. Inventory what is in force, score it against the six capabilities θ is defined as, and let the two instruments disagree in the open.',
    where: 'Existing safeguards; Maturity & resilience', routes: [['safeguards', 'Existing safeguards'], ['maturity', 'Maturity & resilience']],
    steps: ['Existing safeguards → “Add a safeguard”: name it, set the state, name an accountable owner, and state the scope and what it does not cover.',
      'Under “Contribution to resilience”, score the safeguard against each capability. A safeguard marked “Planned” counts for nothing until it operates.',
      'Record when it was last tested with the result; no evidence for twelve months is reported as stale.',
      'If your existing controls are still in the mitigation plan, “Bring controls over” lists them and “Bring the ticked ones into the inventory” moves the ones you tick.',
      'Existing safeguards → “Resilience coverage” shows where the resilience comes from and proposes a θ. Nothing changes until you apply it to a scenario.',
      'Maturity & resilience → “Maturity (CSF 2.0)”: score the categories that matter, against a target. Leave a category blank rather than guessing it. “Fill the unscored ones from the inventory” proposes a level where safeguards point at a CSF category.',
      'Maturity & resilience → “Resilience (θ)”: answer the eighteen questions. “Unknown” is a real answer and is excluded from the score.',
      'Maturity & resilience → “The two readings”: read the gap between the questionnaire and the inventory. The lower θ is offered; apply it per scenario.',
      '“Record it” keeps a dated entry so the next assessment can be compared with this one.'],
    done: 'The inventory covers what is in force, and a θ on each material scenario comes from the assessment rather than from memory.' },
  { h: 'Be honest about confidence', t: 'Give every parameter a rationale and a confidence level; Forecasts turns low confidence into wider ranges.',
    where: 'Scenario editor → the six parameters; Forecasts', routes: [['scenario', 'Scenario editor'], ['forecast', 'Forecasts'], ['ai', 'AI assistant']],
    steps: ['For each of the six parameters give the value, a rationale, the evidence and a confidence (High, Medium, Low). Evidence imported from the documents is added to these fields, never as a number.',
      'Forecasts → “Parameter ranges” → “Propose ranges where none are set” (Low ±0.15, Medium ±0.10, High ±0.05), then “Monte Carlo” → “Run forecast”.',
      'Optional: AI assistant → “Parameter critique” points out confidence the evidence does not support.'],
    done: 'Process step 6 shows Done: 80% of the parameters of the included scenarios carry a rationale.' },
  { h: 'Let the engine calculate', t: 'Residual risk and the ratio come from the verified engine; AI and feeds propose, they never change a score.',
    where: 'Risk calculator; footer', routes: [['calc', 'Risk calculator'], ['threat', 'Threat context']],
    steps: ['Check the footer reads “engine verified · 84,491 / 41,104” at every start.',
      'Read estimated, tolerated, mitigated and residual risk, the ratio and its band in the Risk calculator.',
      'Only accepted proposals change a value; Threat context → “Proposed Pb(ψ,A) changes” is the only path from threat intelligence to a score, for exposed CVEs only.'],
    done: 'The figures you report come from the Risk calculator.' },
  { h: 'Treat what is above tolerance first', t: 'Use Risk mitigation → Proposals on the scenarios above tolerance; shared measures are counted once.',
    where: 'Recommendations → Treatment need; Risk mitigation', routes: [['recs', 'Recommendations'], ['mitigation', 'Risk mitigation']],
    steps: ['Recommendations → “Treatment need”: the verdict against tolerance and a treatment objective per scenario.',
      'Risk mitigation → “Proposals”: tick the scenarios above tolerance and click “Add ticked proposals to the plan” (or pick controls in “Control catalogue”). Existing controls imported from the documents are already there as implemented, with zero reductions until you set them.',
      '“Mitigation plan”: set cost and likelihood / impact reductions; tick the measures to implement and click “→ New draft recommendation”.',
      'A measure covering several scenarios is costed once — see Recommendations → “Shared controls”.'],
    done: 'Process step 8 shows Done: every scenario above tolerance has at least one measure.' },
  { h: 'Get approvals from the accountable person', t: 'Recommendations and risk acceptances are approved by the person who is Accountable (RACI “A”).',
    where: 'Recommendations → Recommendations; Risk register', routes: [['recs', 'Recommendations'], ['riskreg', 'Risk register'], ['settings/users', 'Users & RACI']],
    steps: ['Recommendations → “Recommendations”: move the draft through Draft → In review → Approved, with the approver and a note; approval freezes the figures.',
      'Risk register → the risk → “Formal acceptance” (“Accepted by”, “Rationale, conditions, approval reference”).',
      'In multi-user mode (Settings → “Users & RACI”) only A on step 9, or an administrator, approves and accepts; approving a measure needs A on step 8. “Menu access by group and user account” can further restrict or open screens. “Switch user” is in the top bar.'],
    done: 'Process step 9 shows Done: at least one recommendation approved and every risk has a treatment decision.' },
  { h: 'Keep a baseline and a budget', t: 'Enter the IT budget, the current cybersecurity spend and the baseline (run) cost; the Budget screen shows where each option lands.',
    where: 'Organization → Profile & appetite (bottom); Budget', routes: [['org/profile', 'Profile & appetite'], ['budget', 'Budget']],
    steps: ['Enter “Total IT budget (incl. salaries)”, “Cybersecurity budget (current spend)” and “Baseline (run) security cost”, then “Save”.',
      'Budget: fill the budget year and allocate the initiatives over up to three years; projects imported from the documents are already listed as initiatives.',
      'The band chart places each funding option between risk-averse (4% of IT), neutral (7.8%) and risk-seeking (12%).'],
    done: 'Process step 10 shows Done: the budget year is filled and the initiatives are allocated.' },
  { h: 'Record KRIs at every review', t: 'Four readings are enough for the KRI projection to say whether a threshold will be crossed.',
    where: 'KRI dashboard; Forecasts → KRI projections', routes: [['dashboard', 'KRI dashboard'], ['forecast', 'Forecasts']],
    steps: ['KRI dashboard: “Record a measurement”, or “Record computed + entered values” to capture everything at once. Metrics imported from the documents are the first reading.',
      'Forecasts → “KRI projections”: from 4 readings, the trend with a 95% band and whether a threshold will be crossed.'],
    done: 'Process step 11 shows Done: at least one measurement recorded.' },
  { h: 'Anonymize what leaves', t: 'Publish & share anonymizes; a classroom case is labelled fictional automatically.',
    where: 'Publish & share → Publish a package; Settings → AI — local & remote', routes: [['share', 'Publish & share'], ['settings/ai', 'AI — local & remote']],
    steps: ['Publish & share → “Publish a package”: choose the scope and format, tick “Anonymize this package”, read “Check these before publishing”, then “Publish to the shared registry”.',
      'Classroom and educational cases are labelled fictional in the exports and the workbook.',
      'For AI: Settings → AI — local & remote → “Anonymize before sending”.'],
    done: 'Nothing identifying leaves the computer without a decision.' },
];
